<?php

return [
    'Alberta' => [
        'city_wide' => [
            'display_count' => 19,
            'places' => [
                'Airdrie',
                'Beaumont',
                'Brooks',
                'Calgary',
                'Camrose',
                'Chestermere',
                'Cold Lake',
                'Edmonton',
                'Fort Saskatchewan',
                'Grande Prairie',
                'Lacombe',
                'Leduc',
                'Lethbridge',
                'Lloydminster',
                'Medicine Hat',
                'Red Deer',
                'Spruce Grove',
                'St. Albert',
                'Wetaskiwin',
            ],
        ],
        'municipalities' => [
            'display_count' => 76,
            'places' => [
                // Municipal Districts (MD) and Counties (63)
                'Athabasca County',
                'Beaver County',
                'Big Lakes County',
                'Birch Hills County',
                'Brazeau County',
                'Camrose County',
                'Cardston County',
                'Clear Hills County',
                'Clearwater County',
                'County of Barrhead No. 11',
                'County of Forty Mile No. 8',
                'County of Grande Prairie No. 1',
                'County of Minburn No. 27',
                'County of Newell',
                'County of Northern Lights',
                'County of Paintearth No. 18',
                'County of St. Paul No. 19',
                'County of Stettler No. 6',
                'County of Two Hills No. 21',
                'County of Vermilion River',
                'County of Warner No. 5',
                'County of Wetaskiwin No. 10',
                'Cypress County',
                'Flagstaff County',
                'Foothills County',
                'Kneehill County',
                'Lac Ste. Anne County',
                'Lacombe County',
                'Lamont County',
                'Leduc County',
                'Lethbridge County',
                'MD of Acadia No. 34',
                'MD of Bighorn No. 8',
                'MD of Bonnyville No. 87',
                'MD of Fairview No. 136',
                'MD of Greenview No. 16',
                'MD of Lesser Slave River No. 124',
                'MD of Opportunity No. 17',
                'MD of Peace No. 135',
                'MD of Pincher Creek No. 9',
                'MD of Provost No. 52',
                'MD of Ranchland No. 66',
                'MD of Smoky River No. 130',
                'MD of Spirit River No. 133',
                'MD of Taber',
                'MD of Wainwright No. 61',
                'MD of Willow Creek No. 26',
                'Mountain View County',
                'Northern Sunrise County',
                'Parkland County',
                'Ponoka County',
                'Red Deer County',
                'Rocky View County',
                'Saddle Hills County',
                'Smoky Lake County',
                'Starland County',
                'Sturgeon County',
                'Thorhild County',
                'Vulcan County',
                'Westlock County',
                'Wheatland County',
                'Woodlands County',
                'Yellowhead County',
                // Specialized Municipalities (6)
                'Crowsnest Pass, Municipality of',
                'Jasper, Municipality of',
                'Lac La Biche County',
                'Mackenzie County',
                'Strathcona County',
                'Wood Buffalo, Regional Municipality of',
                // Improvement Districts (7)
                'Improvement District No. 4',
                'Improvement District No. 9',
                'Improvement District No. 12',
                'Improvement District No. 13',
                'Improvement District No. 24',
                'Improvement District No. 25',
                'Kananaskis Improvement District',
            ],
        ],
        'towns' => [
            'display_count' => 105,
            'places' => [
                'Athabasca',
                'Banff',
                'Barrhead',
                'Bashaw',
                'Bassano',
                'Beaverlodge',
                'Bentley',
                'Blackfalds',
                'Bon Accord',
                'Bonnyville',
                'Bow Island',
                'Bowden',
                'Bruderheim',
                'Calmar',
                'Canmore',
                'Cardston',
                'Carstairs',
                'Castor',
                'Claresholm',
                'Coaldale',
                'Coalhurst',
                'Cochrane',
                'Coronation',
                'Crossfield',
                'Daysland',
                'Devon',
                'Diamond Valley',
                'Didsbury',
                'Drayton Valley',
                'Drumheller',
                'Eckville',
                'Edson',
                'Elk Point',
                'Fairview',
                'Falher',
                'Fort Macleod',
                'Fox Creek',
                'Gibbons',
                'Grimshaw',
                'Hanna',
                'Hardisty',
                'High Level',
                'High Prairie',
                'High River',
                'Hinton',
                'Innisfail',
                'Irricana',
                'Killam',
                'Lamont',
                'Legal',
                'Magrath',
                'Manning',
                'Mayerthorpe',
                'McLennan',
                'Milk River',
                'Millet',
                'Morinville',
                'Mundare',
                'Nanton',
                'Nobleford',
                'Okotoks',
                'Olds',
                'Onoway',
                'Oyen',
                'Peace River',
                'Penhold',
                'Picture Butte',
                'Pincher Creek',
                'Ponoka',
                'Provost',
                'Rainbow Lake',
                'Raymond',
                'Redcliff',
                'Redwater',
                'Rimbey',
                'Rocky Mountain House',
                'Sedgewick',
                'Sexsmith',
                'Slave Lake',
                'Smoky Lake',
                'Spirit River',
                'St. Paul',
                'Stavely',
                'Stettler',
                'Stony Plain',
                'Strathmore',
                'Sundre',
                'Swan Hills',
                'Sylvan Lake',
                'Taber',
                'Thorsby',
                'Three Hills',
                'Tofield',
                'Trochu',
                'Two Hills',
                'Valleyview',
                'Vauxhall',
                'Vegreville',
                'Vermilion',
                'Viking',
                'Vulcan',
                'Wainwright',
                'Wembley',
                'Westlock',
                'Whitecourt',
            ],
        ],
        'villages' => [
            'display_count' => 129,
            'places' => [
                // Villages (78)
                'Acme',
                'Alberta Beach',
                'Alix',
                'Alliance',
                'Amisk',
                'Andrew',
                'Arrowwood',
                'Barnwell',
                'Barons',
                'Bawlf',
                'Beiseker',
                'Berwyn',
                'Big Valley',
                'Bittern Lake',
                'Boyle',
                'Breton',
                'Carbon',
                'Carmangay',
                'Champion',
                'Chauvin',
                'Chipman',
                'Clive',
                'Clyde',
                'Consort',
                'Coutts',
                'Cowley',
                'Cremona',
                'Czar',
                'Delburne',
                'Delia',
                'Donalda',
                'Donnelly',
                'Duchess',
                'Edberg',
                'Edgerton',
                'Elnora',
                'Empress',
                'Foremost',
                'Forestburg',
                'Girouxville',
                'Glendon',
                'Glenwood',
                'Hay Lakes',
                'Heisler',
                'Hill Spring',
                'Hines Creek',
                'Holden',
                'Hughenden',
                'Hussar',
                'Innisfree',
                'Irma',
                'Kitscoty',
                'Linden',
                'Lomond',
                'Longview',
                'Lougheed',
                'Mannville',
                'Marwayne',
                'Milo',
                'Morrin',
                'Munson',
                'Myrnam',
                'Nampa',
                'Paradise Valley',
                'Rockyford',
                'Rosalind',
                'Rosemary',
                'Rycroft',
                'Ryley',
                'Spring Lake',
                'Standard',
                'Stirling',
                'Veteran',
                'Vilna',
                'Warburg',
                'Warner',
                'Waskatenau',
                'Youngstown',
                // Summer Villages (51)
                'Argentia Beach',
                'Betula Beach',
                'Birch Cove',
                'Birchcliff',
                'Bondiss',
                'Bonnyville Beach',
                'Burnstick Lake',
                'Castle Island',
                'Crystal Springs',
                'Ghost Lake',
                'Golden Days',
                'Grandview',
                'Gull Lake',
                'Half Moon Bay',
                'Horseshoe Bay',
                'Island Lake',
                'Island Lake South',
                'Itaska Beach',
                'Jarvis Bay',
                'Kapasiwin',
                'Lakeview',
                'Larkspur',
                'Ma-Me-O Beach',
                'Mewatha Beach',
                'Nakamun Park',
                'Norglenwold',
                'Norris Beach',
                'Parkland Beach',
                'Pelican Narrows',
                'Point Alison',
                'Poplar Bay',
                'Rochon Sands',
                'Ross Haven',
                'Sandy Beach',
                'Seba Beach',
                'Silver Beach',
                'Silver Sands',
                'South Baptiste',
                'South View',
                'Sunbreaker Cove',
                'Sundance Beach',
                'Sunrise Beach',
                'Sunset Beach',
                'Sunset Point',
                'Val Quentin',
                'Waiparous',
                'West Baptiste',
                'West Cove',
                'Whispering Hills',
                'White Sands',
                'Yellowstone',
            ],
        ],
        'district_wide' => [
            'display_count' => 19,
            'places' => [
                'Division No. 1',
                'Division No. 2',
                'Division No. 3',
                'Division No. 4',
                'Division No. 5',
                'Division No. 6',
                'Division No. 7',
                'Division No. 8',
                'Division No. 9',
                'Division No. 10',
                'Division No. 11',
                'Division No. 12',
                'Division No. 13',
                'Division No. 14',
                'Division No. 15',
                'Division No. 16',
                'Division No. 17',
                'Division No. 18',
                'Division No. 19',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 148,
        ],
    ],
];
