<?php

return [
    'British Columbia' => [
        'city_wide' => [
            'display_count' => 53,
            'places' => [
                'Abbotsford',
                'Armstrong',
                'Burnaby',
                'Campbell River',
                'Castlegar',
                'Chilliwack',
                'Colwood',
                'Coquitlam',
                'Courtenay',
                'Cranbrook',
                'Dawson Creek',
                'Delta',
                'Duncan',
                'Enderby',
                'Fernie',
                'Fort St. John',
                'Grand Forks',
                'Greenwood',
                'Kamloops',
                'Kelowna',
                'Kimberley',
                'Langford',
                'Langley',
                'Maple Ridge',
                'Merritt',
                'Mission',
                'Nanaimo',
                'Nelson',
                'New Westminster',
                'North Vancouver',
                'Parksville',
                'Penticton',
                'Pitt Meadows',
                'Port Alberni',
                'Port Coquitlam',
                'Port Moody',
                'Powell River',
                'Prince George',
                'Prince Rupert',
                'Quesnel',
                'Revelstoke',
                'Richmond',
                'Rossland',
                'Salmon Arm',
                'Surrey',
                'Terrace',
                'Trail',
                'Vancouver',
                'Vernon',
                'Victoria',
                'West Kelowna',
                'White Rock',
                'Williams Lake',
            ],
        ],
        'municipalities' => [
            'display_count' => 51,
            'places' => [
                '100 Mile House',
                'Barriere',
                'Bowen Island',
                'Central Saanich',
                'Chetwynd',
                'Clearwater',
                'Coldstream',
                'Elkford',
                'Esquimalt',
                'Fort St. James',
                'Highlands',
                'Hope',
                'Houston',
                'Hudson\'s Hope',
                'Invermere',
                'Kent',
                'Kitimat',
                'Lake Country',
                'Langley',
                'Lantzville',
                'Lillooet',
                'Logan Lake',
                'Mackenzie',
                'Metchosin',
                'New Hazelton',
                'North Cowichan',
                'North Saanich',
                'North Vancouver',
                'Northern Rockies',
                'Oak Bay',
                'Peachland',
                'Port Edward',
                'Port Hardy',
                'Saanich',
                'Sechelt',
                'Sicamous',
                'Sooke',
                'Spallumcheen',
                'Sparwood',
                'Squamish',
                'Stewart',
                'Summerland',
                'Sun Peaks',
                'Taylor',
                'Tofino',
                'Tumbler Ridge',
                'Ucluelet',
                'Vanderhoof',
                'Wells',
                'West Vancouver',
                'Whistler',
            ],
        ],
        'towns' => [
            'display_count' => 14,
            'places' => [
                'Comox',
                'Creston',
                'Gibsons',
                'Golden',
                'Ladysmith',
                'Lake Cowichan',
                'Oliver',
                'Osoyoos',
                'Port McNeill',
                'Princeton',
                'Qualicum Beach',
                'Sidney',
                'Smithers',
                'View Royal',
            ],
        ],
        'villages' => [
            'display_count' => 42,
            'places' => [
                'Alert Bay',
                'Anmore',
                'Ashcroft',
                'Belcarra',
                'Burns Lake',
                'Cache Creek',
                'Canal Flats',
                'Chase',
                'Clinton',
                'Cumberland',
                'Daajing Giids',
                'Fraser Lake',
                'Fruitvale',
                'Gold River',
                'Granisle',
                'Harrison Hot Springs',
                'Hazelton',
                'Kaslo',
                'Keremeos',
                'Lions Bay',
                'Lumby',
                'Lytton',
                'Masset',
                'McBride',
                'Midway',
                'Montrose',
                'Nakusp',
                'New Denver',
                'Pemberton',
                'Port Alice',
                'Port Clements',
                'Pouce Coupe',
                'Radium Hot Springs',
                'Salmo',
                'Sayward',
                'Silverton',
                'Slocan',
                'Tahsis',
                'Telkwa',
                'Valemount',
                'Warfield',
                'Zeballos',
            ],
        ],
        'district_wide' => [
            'display_count' => 27,
            'places' => [
                'Alberni-Clayoquot Regional District',
                'Bulkley-Nechako Regional District',
                'Capital Regional District',
                'Cariboo Regional District',
                'Central Coast Regional District',
                'Central Kootenay Regional District',
                'Central Okanagan Regional District',
                'Columbia-Shuswap Regional District',
                'Comox Valley Regional District',
                'Cowichan Valley Regional District',
                'East Kootenay Regional District',
                'Fraser Valley Regional District',
                'Fraser-Fort George Regional District',
                'Kitimat-Stikine Regional District',
                'Kootenay Boundary Regional District',
                'Metro Vancouver Regional District',
                'Mount Waddington Regional District',
                'Nanaimo Regional District',
                'North Coast Regional District',
                'North Okanagan Regional District',
                'Okanagan-Similkameen Regional District',
                'Peace River Regional District',
                'qathet Regional District',
                'Squamish-Lillooet Regional District',
                'Strathcona Regional District',
                'Sunshine Coast Regional District',
                'Thompson-Nicola Regional District',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 1583,
        ],
    ],
];
