<?php

return [
    'New Brunswick' => [
        'city_wide' => [
            'display_count' => 8,
            'places' => [
                'Bathurst',
                'Campbellton',
                'Dieppe',
                'Edmundston',
                'Fredericton',
                'Miramichi',
                'Moncton',
                'Saint John',
            ],
        ],
        'municipalities' => [
            'display_count' => 30,
            'places' => [
                // Rural Communities (17)
                'Alnwick',
                'Beausoleil',
                'Butternut Valley',
                'Campobello Island',
                'Central York',
                'Eastern Charlotte',
                'Fundy Shores',
                'Hanwell',
                'Harvey',
                'Kedgwick',
                'Maple Hills',
                'Miramichi River Valley',
                'Nackawic-Millville',
                'Nashwaak',
                'Strait Shores',
                'Sunbury-York South',
                'Upper Miramichi',
                // Regional Municipality (1)
                'Tracadie',
                // Rural Districts (12)
                'Acadian Peninsula',
                'Capital Region',
                'Chaleur',
                'Fundy',
                'Greater Miramichi',
                'Kent',
                'Kings',
                'Northwest',
                'Restigouche',
                'Southeast',
                'Southwest',
                'Western Valley',
            ],
        ],
        'towns' => [
            'display_count' => 30,
            'places' => [
                'Beaurivage',
                'Belle-Baie',
                'Cap-Acadie',
                'Caraquet',
                'Carleton North',
                'Champdoré',
                'Grand Bay-Westfield',
                'Grand Falls',
                'Grand-Bouctouche',
                'Hampton',
                'Hartland',
                'Haut-Madawaska',
                'Hautes-Terres',
                'Heron Bay',
                'Île-de-Lamèque',
                'Oromocto',
                'Quispamsis',
                'Riverview',
                'Rivière-du-Nord',
                'Rothesay',
                'Saint Andrews',
                'Saint-Quentin',
                'Salisbury',
                'Shediac',
                'Shippagan',
                'St. Stephen',
                'Sussex',
                'Tantramar',
                'Vallée-des-Rivières',
                'Woodstock',
            ],
        ],
        'villages' => [
            'display_count' => 21,
            'places' => [
                'Arcadia',
                'Belledune',
                'Bois-Joli',
                'Doaktown',
                'Five Rivers',
                'Fredericton Junction',
                'Fundy Albert',
                'Fundy-St. Martins',
                'Grand Lake',
                'Grand Manan',
                'Lakeland Ridges',
                'McAdam',
                'Memramcook',
                'Neguac',
                'New Maryland',
                'Nouvelle-Arcadie',
                'Southern Victoria',
                'Three Rivers',
                'Tobique Valley',
                'Tracy',
                'Valley Waters',
            ],
        ],
        'district_wide' => [
            'display_count' => 15,
            'places' => [
                'Albert County',
                'Carleton County',
                'Charlotte County',
                'Gloucester County',
                'Kent County',
                'Kings County',
                'Madawaska County',
                'Northumberland County',
                'Queens County',
                'Restigouche County',
                'Saint John County',
                'Sunbury County',
                'Victoria County',
                'Westmorland County',
                'York County',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 32,
        ],
    ],
];
