<?php

return [
    'Nova Scotia' => [
        'city_wide' => [
            'display_count' => 4,
            'places' => [
                'Cape Breton Regional Municipality',
                'Halifax Regional Municipality',
                'Region of Queens Municipality',
                'West Hants Regional Municipality',
            ],
        ],
        'municipalities' => [
            'display_count' => 20,
            'places' => [
                'Municipality of the County of Annapolis',
                'Municipality of the County of Antigonish',
                'Municipality of the County of Colchester',
                'Municipality of the County of Cumberland',
                'Municipality of the County of Inverness',
                'Municipality of the County of Kings',
                'Municipality of the County of Pictou',
                'Municipality of the County of Richmond',
                'Municipality of the County of Victoria',
                'Municipality of the District of Argyle',
                'Municipality of the District of Barrington',
                'Municipality of the District of Chester',
                'Municipality of the District of Clare',
                'Municipality of the District of Digby',
                'Municipality of the District of East Hants',
                'Municipality of the District of Guysborough',
                'Municipality of the District of Lunenburg',
                'Municipality of the District of Shelburne',
                'Municipality of the District of St. Mary\'s',
                'Municipality of the District of Yarmouth',
            ],
        ],
        'towns' => [
            'display_count' => 25,
            'places' => [
                'Amherst',
                'Annapolis Royal',
                'Antigonish',
                'Berwick',
                'Bridgewater',
                'Clark\'s Harbour',
                'Digby',
                'Kentville',
                'Lockeport',
                'Lunenburg',
                'Mahone Bay',
                'Middleton',
                'Mulgrave',
                'New Glasgow',
                'Oxford',
                'Pictou',
                'Port Hawkesbury',
                'Shelburne',
                'Stellarton',
                'Stewiacke',
                'Trenton',
                'Truro',
                'Westville',
                'Wolfville',
                'Yarmouth',
            ],
        ],
        'district_wide' => [
            'display_count' => 18,
            'places' => [
                'Annapolis County',
                'Antigonish County',
                'Cape Breton County',
                'Colchester County',
                'Cumberland County',
                'Digby County',
                'Guysborough County',
                'Halifax County',
                'Hants County',
                'Inverness County',
                'Kings County',
                'Lunenburg County',
                'Pictou County',
                'Queens County',
                'Richmond County',
                'Shelburne County',
                'Victoria County',
                'Yarmouth County',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 34,
        ],
    ],
];
