<?php

return [
    'Ontario' => [
        'city_wide' => [
            'display_count' => 52,
            'places' => [
                'Barrie',
                'Belleville',
                'Brampton',
                'Brant',
                'Brantford',
                'Brockville',
                'Burlington',
                'Cambridge',
                'Clarence-Rockland',
                'Cornwall',
                'Dryden',
                'Elliot Lake',
                'Greater Sudbury',
                'Guelph',
                'Haldimand County',
                'Hamilton',
                'Kawartha Lakes',
                'Kenora',
                'Kingston',
                'Kitchener',
                'London',
                'Markham',
                'Mississauga',
                'Niagara Falls',
                'Norfolk County',
                'North Bay',
                'Orillia',
                'Oshawa',
                'Ottawa',
                'Owen Sound',
                'Pembroke',
                'Peterborough',
                'Pickering',
                'Port Colborne',
                'Prince Edward County',
                'Quinte West',
                'Richmond Hill',
                'Sarnia',
                'Sault Ste. Marie',
                'St. Catharines',
                'St. Thomas',
                'Stratford',
                'Temiskaming Shores',
                'Thorold',
                'Thunder Bay',
                'Timmins',
                'Toronto',
                'Vaughan',
                'Waterloo',
                'Welland',
                'Windsor',
                'Woodstock',
            ],
        ],
        'municipalities' => [
            'display_count' => 262,
            'places' => [
                // Municipality status (64)
                'Arran-Elderslie',
                'Bayham',
                'Bluewater',
                'Brighton',
                'Brockton',
                'Brooke-Alvinston',
                'Callander',
                'Calvin',
                'Central Elgin',
                'Central Huron',
                'Central Manitoulin',
                'Centre Hastings',
                'Chatham-Kent',
                'Clarington',
                'Dysart et al',
                'French River',
                'Gordon/Barrie Island',
                'Greenstone',
                'Grey Highlands',
                'Hastings Highlands',
                'Highlands East',
                'Huron East',
                'Huron Shores',
                'Killarney',
                'Kincardine',
                'Lambton Shores',
                'Leamington',
                'Magnetawan',
                'Markstay-Warren',
                'Marmora and Lake',
                'Meaford',
                'Middlesex Centre',
                'Morris-Turnberry',
                'Neebing',
                'Northeastern Manitoulin and the Islands',
                'Northern Bruce Peninsula',
                'North Grenville',
                'North Middlesex',
                'North Perth',
                'Oliver Paipoonge',
                'Port Hope',
                'Powassan',
                'Red Lake',
                'Shuniah',
                'Sioux Lookout',
                'South Bruce',
                'South Dundas',
                'South Huron',
                'Southwest Middlesex',
                'St.-Charles',
                'Strathroy-Caradoc',
                'Temagami',
                'Thames Centre',
                'Casselman',
                'The Nation',
                'Trent Hills',
                'Trent Lakes',
                'Tweed',
                'Wawa',
                'West Elgin',
                'West Grey',
                'West Nipissing',
                'West Perth',
                'Whitestone',
                // Lower-tier Townships (114)
                'Addington Highlands',
                'Adelaide-Metcalfe',
                'Adjala-Tosorontio',
                'Admaston/Bromley',
                'Alfred and Plantagenet',
                'Algonquin Highlands',
                'Alnwick/Haldimand',
                'Amaranth',
                'Ashfield-Colborne-Wawanosh',
                'Asphodel-Norwood',
                'Athens',
                'Augusta',
                'Beckwith',
                'Blandford-Blenheim',
                'Bonnechere Valley',
                'Brock',
                'Brudenell/Lyndoch and Raglan',
                'Carlow/Mayo',
                'Cavan-Monaghan',
                'Central Frontenac',
                'Centre Wellington',
                'Champlain',
                'Chatsworth',
                'Clearview',
                'Cramahe',
                'Dawn-Euphemia',
                'Douro-Dummer',
                'Drummond/North Elmsley',
                'East Garafraxa',
                'East Hawkesbury',
                'East Zorra-Tavistock',
                'Edwardsburgh/Cardinal',
                'Elizabethtown-Kitley',
                'Enniskillen',
                'Essa',
                'Faraday',
                'Front of Yonge',
                'Frontenac Islands',
                'Georgian Bay',
                'Georgian Bluffs',
                'Greater Madawaska',
                'Guelph/Eramosa',
                'Hamilton Township',
                'Havelock-Belmont-Methuen',
                'Head/Clara and Maria',
                'Horton',
                'Howick',
                'Huron-Kinloss',

                'Killaloe, Hagarty and Richards',
                'King',
                'Lake of Bays',
                'Lanark Highlands',
                'Laurentian Valley',
                'Leeds and the Thousand Islands',
                'Limerick',
                'Loyalist',
                'Lucan Biddulph',
                'Madawaska Valley',
                'Madoc',
                'Malahide',
                'Mapleton',
                'McNab/Braeside',
                'Melancthon',
                'Minden Hills',
                'Montague',
                'Mulmur',
                'Muskoka Lakes',
                'North Algona Wilberforce',
                'North Dumfries',
                'North Dundas',
                'North Frontenac',
                'North Glengarry',
                'North Huron',
                'North Kawartha',
                'North Stormont',
                'Norwich',
                'Oro-Medonte',
                'Otonabee-South Monaghan',
                'Perth East',
                'Perth South',
                'Puslinch',
                'Ramara',
                'Rideau Lakes',
                'Russell',
                'Scugog',
                'Selwyn',
                'Severn',
                'South Frontenac',
                'South Glengarry',
                'South Stormont',
                'Southgate',
                'South-West Oxford',
                'Southwold',
                'Springwater',
                'St. Clair',
                'Stirling-Rawdon',
                'Stone Mills',
                'Tay',
                'Tay Valley',
                'Tiny',
                'Tudor and Cashel',
                'Tyendinaga',
                'Uxbridge',
                'Wainfleet',
                'Warwick',
                'Wellesley',
                'Wellington North',
                'West Lincoln',
                'Whitewater Region',
                'Wilmot',
                'Woolwich',
                'Zorra',
                // Single-tier Townships (86)
                'Alberton',
                'The Archipelago',
                'Armour',
                'Armstrong',
                'Assiginack',
                'Baldwin',
                'Billings',
                'Black River-Matheson',
                'Bonfield',
                'Brethour',
                'Burpee and Mills',
                'Carling',
                'Casey',
                'Chamberlain',
                'Chapleau',
                'Chapple',
                'Chisholm',
                'Cockburn Island',
                'Coleman',
                'Conmee',
                'Dawson',
                'Dorion',
                'Dubreuilville',
                'Ear Falls',
                'East Ferris',
                'Emo',
                'Evanturel',
                'Fauquier-Strickland',
                'Gauthier',
                'Gillies',
                'Harley',
                'Harris',
                'Hilliard',
                'Hilton',
                'Hornepayne',
                'Hudson',
                'Ignace',
                'James',
                'Jocelyn',
                'Johnson',
                'Joly',
                'Kerns',
                'La Vallee',
                'Laird',
                'Lake of the Woods',
                'Larder Lake',
                'Macdonald/Meredith and Aberdeen Additional',
                'Machar',
                'Machin',
                'Manitouwadge',
                'Matachewan',
                'Mattawan',
                'Mattice-Val Côté',
                'McDougall',
                'McGarry',
                'McKellar',
                'McMurrich/Monteith',
                'Moonbeam',
                'Morley',
                'Nairn and Hyman',
                'Nipigon',
                'Nipissing',
                'North Algonquin',
                'The North Shore',
                'O\'Connor',
                'Opasatika',
                'Papineau-Cameron',
                'Pelee',
                'Perry',
                'Pickle Lake',
                'Plummer Additional',
                'Prince',
                'Red Rock',
                'Ryerson',
                'Sables-Spanish Rivers',
                'Schreiber',
                'Seguin',
                'Sioux Narrows-Nestor Falls',
                'South Algonquin',
                'St. Joseph',
                'Strong',
                'Tarbutt',
                'Tehkummah',
                'Terrace Bay',
                'Val Rita-Harty',
                'White River',
            ],
        ],
        'towns' => [
            'display_count' => 88,
            'places' => [
                'Ajax',
                'Amherstburg',
                'Arnprior',
                'Atikokan',
                'Aurora',
                'Aylmer',
                'Bancroft',
                'Blind River',
                'Bracebridge',
                'Bradford West Gwillimbury',
                'Bruce Mines',
                'Caledon',
                'Carleton Place',
                'Cobalt',
                'Cobourg',
                'Cochrane',
                'Collingwood',
                'Deep River',
                'Deseronto',
                'East Gwillimbury',
                'Englehart',
                'Erin',
                'Espanola',
                'Essex',
                'Fort Erie',
                'Fort Frances',
                'Gananoque',
                'Georgina',
                'Goderich',
                'Gore Bay',
                'Grand Valley',
                'Gravenhurst',
                'Greater Napanee',
                'Grimsby',
                'Halton Hills',
                'Hanover',
                'Hawkesbury',
                'Hearst',
                'Huntsville',
                'Ingersoll',
                'Innisfil',
                'Iroquois Falls',
                'Kapuskasing',
                'Kearney',
                'Kingsville',
                'Kirkland Lake',
                'Lakeshore',
                'LaSalle',
                'Latchford',
                'Laurentian Hills',
                'Lincoln',
                'Marathon',
                'Mattawa',
                'Midland',
                'Milton',
                'Minto',
                'Mississippi Mills',
                'Mono',
                'Moosonee',
                'New Tecumseth',
                'Newmarket',
                'Niagara-on-the-Lake',
                'Oakville',
                'Orangeville',
                'Parry Sound',
                'Pelham',
                'Penetanguishene',
                'Perth',
                'Petawawa',
                'Petrolia',
                'Plympton-Wyoming',
                'Prescott',
                'Rainy River',
                'Renfrew',
                'Saugeen Shores',
                'Shelburne',
                'Smiths Falls',
                'Smooth Rock Falls',
                'South Bruce Peninsula',
                'Spanish',
                'St. Marys',
                'Tecumseh',
                'The Blue Mountains',
                'Thessalon',
                'Tillsonburg',
                'Wasaga Beach',
                'Whitby',
                'Whitchurch-Stouffville',
            ],
        ],
        'villages' => [
            'display_count' => 11,
            'places' => [
                'Burk\'s Falls',
                'Hilton Beach',
                'Merrickville-Wolford',
                'Morewood',
                'Newbury',
                'Oil Springs',
                'Point Edward',
                'South River',
                'Sundridge',
                'Thornloe',
                'Westport',
            ],
        ],
        'district_wide' => [
            'display_count' => 40,
            'places' => [
                // Counties (19)
                'County of Bruce',
                'County of Dufferin',
                'County of Elgin',
                'County of Essex',
                'County of Frontenac',
                'County of Grey',
                'County of Haliburton',
                'County of Hastings',
                'County of Huron',
                'County of Lambton',
                'County of Lanark',
                'County of Lennox and Addington',
                'County of Middlesex',
                'County of Northumberland',
                'County of Oxford',
                'County of Perth',
                'County of Peterborough',
                'County of Renfrew',
                'County of Simcoe',
                'County of Wellington',
                // United Counties (3)
                'United Counties of Leeds and Grenville',
                'United Counties of Prescott and Russell',
                'United Counties of Stormont, Dundas and Glengarry',
                // Regional Municipalities (8)
                'District Municipality of Muskoka',
                'Regional Municipality of Durham',
                'Regional Municipality of Halton',
                'Regional Municipality of Niagara',
                'Regional Municipality of Peel',
                'Regional Municipality of Waterloo',
                'Regional Municipality of York',
                // Districts (10) — Northern Ontario unorganized areas
                'Algoma District',
                'Cochrane District',
                'Kenora District',
                'Manitoulin District',
                'Nipissing District',
                'Parry Sound District',
                'Rainy River District',
                'Sudbury District',
                'Thunder Bay District',
                'Timiskaming District',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 207,
        ],
    ],
];
