<?php

return [
    'Prince Edward Island' => [
        'city_wide' => [
            'display_count' => 2,
            'places' => [
                'Charlottetown',
                'Summerside',
            ],
        ],
        'municipalities' => [
            'display_count' => 45,
            'places' => [
                'Abram-Village',
                'Alexandra',
                'Annandale-Little Pond-Howe Bay',
                'Bedeque and Area',
                'Belfast',
                'Brackley',
                'Breadalbane',
                'Central Kings',
                'Central Prince',
                'Clyde River',
                'Crapaud',
                'Eastern Kings',
                'Greenmount-Montrose',
                'Hampshire',
                'Hazelbrook',
                'Hunter River',
                'Kingston',
                'Kinkora',
                'Linkletter',
                'Lot 11 and Area',
                'Malpeque Bay',
                'Miltonvale Park',
                'Miminegash',
                'Miscouche',
                'Morell',
                'Mount Stewart',
                'Murray Harbour',
                'Murray River',
                'North Shore',
                'North Wiltshire',
                'Northport',
                'Resort Municipality of Stanley Bridge, Hope River, Bayview, Cavendish and North Rustico',
                'Sherbrooke',
                'Souris West',
                'St. Felix',
                'St. Nicholas',
                'St. Peters Bay',
                'Tignish Shore',
                'Tyne Valley',
                'Union Road',
                'Victoria',
                'Warren Grove',
                'Wellington',
                'West River',
                'York',
            ],
        ],
        'towns' => [
            'display_count' => 10,
            'places' => [
                'Alberton',
                'Borden-Carleton',
                'Cornwall',
                'Kensington',
                'North Rustico',
                'O\'Leary',
                'Souris',
                'Stratford',
                'Three Rivers',
                'Tignish',
            ],
        ],
        'district_wide' => [
            'display_count' => 3,
            'places' => [
                'Kings County',
                'Prince County',
                'Queens County',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 6,
        ],
    ],
];
