<?php

return [
    'Quebec' => [
        'city_wide' => [
            'display_count' => 234,
            'places' => [
                'Acton Vale',
                'Alma',
                'Amos',
                'Amqui',
                'Baie-Comeau',
                'Baie-D\'Urfé',
                'Baie-Saint-Paul',
                'Barkmere',
                'Beaconsfield',
                'Beauceville',
                'Beauharnois',
                'Beaupré',
                'Bécancour',
                'Bedford',
                'Belleterre',
                'Beloeil',
                'Berthierville',
                'Blainville',
                'Boisbriand',
                'Bois-des-Filion',
                'Bonaventure',
                'Boucherville',
                'Bromont',
                'Brossard',
                'Brownsburg-Chatham',
                'Candiac',
                'Cap-Chat',
                'Cap-Santé',
                'Carignan',
                'Carleton-sur-Mer',
                'Causapscal',
                'Chambly',
                'Chandler',
                'Chapais',
                'Charlemagne',
                'Château-Richer',
                'Châteauguay',
                'Chibougamau',
                'Clermont',
                'Coaticook',
                'Contrecoeur',
                'Cookshire-Eaton',
                'Coteau-du-Lac',
                'Côte-Saint-Luc',
                'Cowansville',
                'Crabtree',
                'Danville',
                'Daveluyville',
                'Dégelis',
                'Delson',
                'Desbiens',
                'Deux-Montagnes',
                'Disraeli',
                'Dolbeau-Mistassini',
                'Dollard-des-Ormeaux',
                'Donnacona',
                'Dorval',
                'Drummondville',
                'Dunham',
                'Duparquet',
                'East Angus',
                'Estérel',
                'Farnham',
                'Fermont',
                'Forestville',
                'Fossambault-sur-le-Lac',
                'Gaspé',
                'Gatineau',
                'Gracefield',
                'Granby',
                'Grande-Rivière',
                'Hampstead',
                'Hudson',
                'Huntingdon',
                'Joliette',
                'Kingsey Falls',
                'Kirkland',
                'L\'Ancienne-Lorette',
                'L\'Assomption',
                'L\'Épiphanie',
                'L\'Île-Cadieux',
                'L\'Île-Dorval',
                'L\'Île-Perrot',
                'La Malbaie',
                'La Pocatière',
                'La Prairie',
                'La Sarre',
                'La Tuque',
                'Lac-Brome',
                'Lac-Delage',
                'Lac-des-Aigles',
                'Lac-Mégantic',
                'Lac-Saint-Joseph',
                'Lac-Sergent',
                'Lachute',
                'Laval',
                'Lavaltrie',
                'Lebel-sur-Quévillon',
                'Léry',
                'Lévis',
                'Longueuil',
                'Lorraine',
                'Louiseville',
                'Macamic',
                'Magog',
                'Malartic',
                'Maniwaki',
                'Marieville',
                'Mascouche',
                'Matagami',
                'Matane',
                'McMasterville',
                'Mercier',
                'Métabetchouan--Lac-à-la-Croix',
                'Métis-sur-Mer',
                'Mirabel',
                'Mont-Joli',
                'Mont-Laurier',
                'Mont-Royal',
                'Mont-Saint-Hilaire',
                'Mont-Tremblant',
                'Montmagny',
                'Montréal',
                'Montréal-Est',
                'Montréal-Ouest',
                'Murdochville',
                'Neuville',
                'New Richmond',
                'Nicolet',
                'Normandin',
                'Notre-Dame-de-l\'Île-Perrot',
                'Notre-Dame-des-Prairies',
                'Otterburn Park',
                'Paspébiac',
                'Percé',
                'Pincourt',
                'Plessisville',
                'Pohénégamook',
                'Pointe-Claire',
                'Pont-Rouge',
                'Port-Cartier',
                'Portneuf',
                'Prévost',
                'Princeville',
                'Québec',
                'Repentigny',
                'Richelieu',
                'Richmond',
                'Rigaud',
                'Rimouski',
                'Rivière-du-Loup',
                'Rivière-Rouge',
                'Roberval',
                'Rosemère',
                'Rouyn-Noranda',
                'Saguenay',
                'Saint-Amable',
                'Saint-Antonin',
                'Saint-Augustin-de-Desmaures',
                'Saint-Basile',
                'Saint-Basile-le-Grand',
                'Saint-Bruno-de-Montarville',
                'Saint-Césaire',
                'Saint-Charles-Borromée',
                'Saint-Colomban',
                'Saint-Constant',
                'Saint-Eustache',
                'Saint-Félicien',
                'Saint-Gabriel',
                'Saint-Georges',
                'Saint-Honoré',
                'Saint-Hyacinthe',
                'Saint-Jean-sur-Richelieu',
                'Saint-Jérôme',
                'Saint-Joseph-de-Beauce',
                'Saint-Joseph-de-Sorel',
                'Saint-Lambert',
                'Saint-Lazare',
                'Saint-Lin--Laurentides',
                'Saint-Marc-des-Carrières',
                'Saint-Ours',
                'Saint-Pamphile',
                'Saint-Pascal',
                'Saint-Philippe',
                'Saint-Pie',
                'Saint-Raymond',
                'Saint-Rémi',
                'Saint-Sauveur',
                'Saint-Tite',
                'Saint-Zotique',
                'Sainte-Adèle',
                'Sainte-Agathe-des-Monts',
                'Sainte-Anne-de-Beaupré',
                'Sainte-Anne-de-Bellevue',
                'Sainte-Anne-des-Monts',
                'Sainte-Anne-des-Plaines',
                'Sainte-Brigitte-de-Laval',
                'Sainte-Catherine',
                'Sainte-Catherine-de-la-Jacques-Cartier',
                'Sainte-Julie',
                'Sainte-Marguerite-du-Lac-Masson',
                'Sainte-Marie',
                'Sainte-Marthe-sur-le-Lac',
                'Sainte-Thérèse',
                'Salaberry-de-Valleyfield',
                'Schefferville',
                'Scotstown',
                'Senneterre',
                'Sept-Îles',
                'Shannon',
                'Shawinigan',
                'Sherbrooke',
                'Sorel-Tracy',
                'Stanstead',
                'Sutton',
                'Témiscaming',
                'Témiscouata-sur-le-Lac',
                'Terrebonne',
                'Thetford Mines',
                'Thurso',
                'Trois-Pistoles',
                'Trois-Rivières',
                'Valcourt',
                'Val-d\'Or',
                'Val-des-Sources',
                'Varennes',
                'Vaudreuil-Dorion',
                'Victoriaville',
                'Ville-Marie',
                'Warwick',
                'Waterloo',
                'Waterville',
                'Westmount',
                'Windsor',
            ],
        ],
        'municipalities' => [
            'display_count' => 652,
            'places' => [
                'Adstock',
                'Aguanish',
                'Albanel',
                'Albertville',
                'Alleyn-et-Cawood',
                'L\'Ange-Gardien',
                'Ange-Gardien',
                'L\'Anse-Saint-Jean',
                'Armagh',
                'L\'Ascension',
                'L\'Ascension-de-Patapédia',
                'Ascot Corner',
                'Aston-Jonction',
                'Auclair',
                'Audet',
                'Austin',
                'Authier',
                'Authier-Nord',
                'L\'Avenir',
                'Baie-des-Sables',
                'Baie-du-Febvre',
                'Baie-Johan-Beetz',
                'Baie-Sainte-Catherine',
                'Barnston-Ouest',
                'Barraute',
                'Batiscan',
                'Béarn',
                'Beaulac-Garthby',
                'Beaumont',
                'Bégin',
                'Belcourt',
                'Les Bergeronnes',
                'Berry',
                'Berthier-sur-Mer',
                'Béthanie',
                'Biencourt',
                'Blanc-Sablon',
                'Blue Sea',
                'Boileau',
                'Bois-Franc',
                'Boischatel',
                'Bonne-Espérance',
                'Bonsecours',
                'La Bostonnais',
                'Bouchette',
                'Bowman',
                'Brigham',
                'Bristol',
                'Bryson',
                'Bury',
                'Cacouna',
                'Calixa-Lavallée',
                'Campbell\'s Bay',
                'Cantley',
                'Cap-Saint-Ignace',
                'Caplan',
                'Cascapédia--Saint-Jules',
                'Cayamant',
                'Les Cèdres',
                'Chambord',
                'Champlain',
                'Champneuf',
                'Charette',
                'Chartierville',
                'Chazel',
                'Chelsea',
                'Chénéville',
                'Chertsey',
                'Chesterville',
                'Chute-Saint-Philippe',
                'Clarenceville',
                'Clarendon',
                'Clerval',
                'Colombier',
                'Compton',
                'La Conception',
                'La Corne',
                'Côte-Nord-du-Golfe-du-Saint-Laurent',
                'Les Coteaux',
                'Courcelles--Saint-Évariste',
                'Déléage',
                'Denholm',
                'Deschaillons-sur-Saint-Laurent',
                'Deschambault-Grondines',
                'Dixville',
                'Dosquet',
                'Dudswell',
                'Duhamel',
                'Duhamel-Ouest',
                'Dupuy',
                'Durham-Sud',
                'East Bolton',
                'East Broughton',
                'East Farnham',
                'East Hereford',
                'Eastman',
                'Les Éboulements',
                'Egan-Sud',
                'Elgin',
                'Entrelacs',
                'Les Escoumins',
                'Escuminac',
                'Esprit-Saint',
                'Fassett',
                'Ferland-et-Boilleau',
                'Ferme-Neuve',
                'Fortierville',
                'Frampton',
                'Franklin',
                'Franquelin',
                'Frelighsburg',
                'Frontenac',
                'Fugèreville',
                'Gallichan',
                'Girardville',
                'Grand-Métis',
                'Grand-Remous',
                'Grand-Saint-Esprit',
                'Grande-Vallée',
                'Grenville-sur-la-Rouge',
                'Gros-Mécatina',
                'Grosse-Île',
                'Grosses-Roches',
                'Ham-Sud',
                'Hatley',
                'Les Hauteurs',
                'Havre-Saint-Pierre',
                'Hébertville',
                'Henryville',
                'Hinchinbrooke',
                'Honfleur',
                'Hope Town',
                'Howick',
                'Huberdeau',
                'L\'Île-d\'Anticosti',
                'L\'Île-du-Grand-Calumet',
                'Les Îles-de-la-Madeleine',
                'Inverness',
                'Irlande',
                'L\'Isle-aux-Allumettes',
                'L\'Isle-aux-Coudres',
                'L\'Isle-Verte',
                'L\'Islet',
                'Ivry-sur-le-Lac',
                'Kamouraska',
                'Kazabazua',
                'Kiamika',
                'Kinnear\'s Mills',
                'Kipawa',
                'Labelle',
                'Labrecque',
                'Lac-au-Saumon',
                'Lac-Beauport',
                'Lac-Bouchette',
                'Lac-des-Écorces',
                'Lac-des-Plages',
                'Lac-des-Seize-Îles',
                'Lac-Drolet',
                'Lac-du-Cerf',
                'Lac-Édouard',
                'Lac-Etchemin',
                'Lac-Frontière',
                'Lac-Saint-Paul',
                'Lac-Sainte-Marie',
                'Lac-Simon',
                'Lac-Supérieur',
                'Lac-Tremblant-Nord',
                'Lacolle',
                'Laforce',
                'Lamarche',
                'Lambton',
                'Lanoraie',
                'Lantier',
                'Larouche',
                'Laurierville',
                'Laverlochère-Angliers',
                'Leclercville',
                'Lefebvre',
                'Lejeune',
                'Lemieux',
                'Litchfield',
                'Longue-Pointe-de-Mingan',
                'Longue-Rive',
                'Lorrainville',
                'Lotbinière',
                'Lyster',
                'La Macaza',
                'Maddington Falls',
                'Mandeville',
                'Manseau',
                'Mansfield-et-Pontefract',
                'Maria',
                'Maricourt',
                'Martinville',
                'La Martre',
                'Maskinongé',
                'Matapédia',
                'Mayo',
                'Les Méchins',
                'Messines',
                'Milan',
                'Mille-Isles',
                'La Minerve',
                'Moffet',
                'Mont-Blanc',
                'Mont-Carmel',
                'Mont-Saint-Grégoire',
                'Mont-Saint-Michel',
                'Montcalm',
                'Montcerf-Lytton',
                'Montebello',
                'Montpellier',
                'La Morandière-Rochebaucourt',
                'Morin-Heights',
                'La Motte',
                'Mulgrave-et-Derry',
                'Namur',
                'Nantes',
                'Napierville',
                'Natashquan',
                'New Carlisle',
                'Newport',
                'Nominingue',
                'Normétal',
                'Notre-Dame-de-Bonsecours',
                'Notre-Dame-de-Ham',
                'Notre-Dame-de-la-Merci',
                'Notre-Dame-de-la-Paix',
                'Notre-Dame-de-la-Salette',
                'Notre-Dame-de-Lorette',
                'Notre-Dame-de-Lourdes',
                'Notre-Dame-de-Montauban',
                'Notre-Dame-de-Pontmain',
                'Notre-Dame-de-Stanbridge',
                'Notre-Dame-des-Bois',
                'Notre-Dame-des-Monts',
                'Notre-Dame-des-Neiges',
                'Notre-Dame-du-Laus',
                'Notre-Dame-du-Nord',
                'Notre-Dame-du-Portage',
                'Notre-Dame-du-Rosaire',
                'Nouvelle',
                'Noyan',
                'Ogden',
                'Oka',
                'Otter Lake',
                'Padoue',
                'Palmarolle',
                'Papineauville',
                'La Patrie',
                'La Pêche',
                'Péribonka',
                'Petit-Saguenay',
                'Petite-Rivière-Saint-François',
                'Petite-Vallée',
                'Piedmont',
                'Pierreville',
                'Pike River',
                'Piopolis',
                'Plaisance',
                'Pointe-à-la-Croix',
                'Pointe-Calumet',
                'Pontiac',
                'Port-Daniel--Gascons',
                'Portneuf-sur-Mer',
                'Poularies',
                'Preissac',
                'La Présentation',
                'Racine',
                'Rapide-Danseur',
                'Rapides-des-Joachims',
                'Rawdon',
                'La Reine',
                'Rémigny',
                'Ripon',
                'Ristigouche-Sud-Est',
                'Rivière-à-Claude',
                'Rivière-à-Pierre',
                'Rivière-au-Tonnerre',
                'Rivière-Beaudette',
                'Rivière-Bleue',
                'Rivière-Éternité',
                'Rivière-Héva',
                'Rivière-Ouelle',
                'Rivière-Saint-Jean',
                'Roquemaure',
                'Rougemont',
                'Roxton Pond',
                'Sacré-Coeur',
                'Saint-Adalbert',
                'Saint-Adolphe-d\'Howard',
                'Saint-Adrien',
                'Saint-Adrien-d\'Irlande',
                'Saint-Agapit',
                'Saint-Aimé',
                'Saint-Aimé-des-Lacs',
                'Saint-Aimé-du-Lac-des-Îles',
                'Saint-Alban',
                'Saint-Albert',
                'Saint-Alexandre',
                'Saint-Alexandre-de-Kamouraska',
                'Saint-Alexis',
                'Saint-Alexis-de-Matapédia',
                'Saint-Alfred',
                'Saint-Alphonse',
                'Saint-Alphonse-de-Granby',
                'Saint-Alphonse-Rodriguez',
                'Saint-Ambroise',
                'Saint-Ambroise-de-Kildare',
                'Saint-André-Avellin',
                'Saint-André-d\'Argenteuil',
                'Saint-André-de-Kamouraska',
                'Saint-André-de-Restigouche',
                'Saint-Anicet',
                'Saint-Anselme',
                'Saint-Antoine-de-Tilly',
                'Saint-Antoine-sur-Richelieu',
                'Saint-Apollinaire',
                'Saint-Armand',
                'Saint-Athanase',
                'Saint-Aubert',
                'Saint-Augustin',
                'Saint-Barnabé-Sud',
                'Saint-Benjamin',
                'Saint-Benoît-du-Lac',
                'Saint-Benoît-Labre',
                'Saint-Bernard',
                'Saint-Bernard-de-Lacolle',
                'Saint-Bernard-de-Michaudville',
                'Saint-Blaise-sur-Richelieu',
                'Saint-Bonaventure',
                'Saint-Boniface',
                'Saint-Bruno',
                'Saint-Bruno-de-Guigues',
                'Saint-Bruno-de-Kamouraska',
                'Saint-Calixte',
                'Saint-Casimir',
                'Saint-Célestin',
                'Saint-Charles-de-Bellechasse',
                'Saint-Charles-de-Bourget',
                'Saint-Charles-sur-Richelieu',
                'Saint-Chrysostome',
                'Saint-Claude',
                'Saint-Cléophas-de-Brandon',
                'Saint-Clet',
                'Saint-Côme',
                'Saint-Côme--Linière',
                'Saint-Cuthbert',
                'Saint-Cyprien',
                'Saint-Cyprien-de-Napierville',
                'Saint-Cyrille-de-Wendover',
                'Saint-Damase',
                'Saint-Damase-de-L\'Islet',
                'Saint-David',
                'Saint-David-de-Falardeau',
                'Saint-Denis-De La Bouteillerie',
                'Saint-Denis-de-Brompton',
                'Saint-Denis-sur-Richelieu',
                'Saint-Dominique',
                'Saint-Dominique-du-Rosaire',
                'Saint-Donat',
                'Saint-Edmond-de-Grantham',
                'Saint-Edmond-les-Plaines',
                'Saint-Édouard',
                'Saint-Édouard-de-Maskinongé',
                'Saint-Élie-de-Caxton',
                'Saint-Elzéar',
                'Saint-Elzéar-de-Témiscouata',
                'Saint-Émile-de-Suffolk',
                'Saint-Éphrem-de-Beauce',
                'Saint-Épiphane',
                'Saint-Esprit',
                'Saint-Étienne-de-Beauharnois',
                'Saint-Étienne-de-Bolton',
                'Saint-Eugène',
                'Saint-Eugène-d\'Argentenay',
                'Saint-Eugène-de-Guigues',
                'Saint-Félix-d\'Otis',
                'Saint-Félix-de-Dalquier',
                'Saint-Félix-de-Kingsey',
                'Saint-Félix-de-Valois',
                'Saint-Ferdinand',
                'Saint-Ferréol-les-Neiges',
                'Saint-Flavien',
                'Saint-Fortunat',
                'Saint-François-d\'Assise',
                'Saint-François-de-l\'Île-d\'Orléans',
                'Saint-François-de-la-Rivière-du-Sud',
                'Saint-François-de-Sales',
                'Saint-François-du-Lac',
                'Saint-François-Xavier-de-Brompton',
                'Saint-François-Xavier-de-Viger',
                'Saint-Fulgence',
                'Saint-Gabriel-de-Brandon',
                'Saint-Gabriel-de-Rimouski',
                'Saint-Gabriel-de-Valcartier',
                'Saint-Gabriel-Lalemant',
                'Saint-Gédéon',
                'Saint-Gédéon-de-Beauce',
                'Saint-Georges-de-Windsor',
                'Saint-Germain-de-Grantham',
                'Saint-Gervais',
                'Saint-Gilles',
                'Saint-Guillaume',
                'Saint-Guy',
                'Saint-Henri',
                'Saint-Henri-de-Taillon',
                'Saint-Herménégilde',
                'Saint-Hippolyte',
                'Saint-Honoré-de-Shenley',
                'Saint-Honoré-de-Témiscouata',
                'Saint-Hubert-de-Rivière-du-Loup',
                'Saint-Hugues',
                'Saint-Ignace-de-Loyola',
                'Saint-Ignace-de-Stanbridge',
                'Saint-Irénée',
                'Saint-Isidore',
                'Saint-Isidore-de-Clifton',
                'Saint-Jacques',
                'Saint-Jacques-de-Leeds',
                'Saint-Jacques-le-Mineur',
                'Saint-Janvier-de-Joly',
                'Saint-Jean-Baptiste',
                'Saint-Jean-de-Brébeuf',
                'Saint-Jean-de-Dieu',
                'Saint-Jean-de-l\'Île-d\'Orléans',
                'Saint-Jean-de-la-Lande',
                'Saint-Jean-de-Matha',
                'Saint-Jean-Port-Joli',
                'Saint-Joachim-de-Shefford',
                'Saint-Joseph-de-Coleraine',
                'Saint-Joseph-des-Érables',
                'Saint-Joseph-du-Lac',
                'Saint-Jude',
                'Saint-Julien',
                'Saint-Just-de-Bretenières',
                'Saint-Juste-du-Lac',
                'Saint-Justin',
                'Saint-Lambert-de-Lauzon',
                'Saint-Laurent-de-l\'Île-d\'Orléans',
                'Saint-Lazare-de-Bellechasse',
                'Saint-Léonard-d\'Aston',
                'Saint-Léonard-de-Portneuf',
                'Saint-Liboire',
                'Saint-Liguori',
                'Saint-Louis',
                'Saint-Louis-de-Blandford',
                'Saint-Luc-de-Bellechasse',
                'Saint-Luc-de-Vincennes',
                'Saint-Lucien',
                'Saint-Ludger',
                'Saint-Ludger-de-Milot',
                'Saint-Magloire',
                'Saint-Malo',
                'Saint-Marc-sur-Richelieu',
                'Saint-Marcel',
                'Saint-Marcel-de-Richelieu',
                'Saint-Mathias-sur-Richelieu',
                'Saint-Mathieu',
                'Saint-Mathieu-d\'Harricana',
                'Saint-Mathieu-de-Beloeil',
                'Saint-Mathieu-de-Rioux',
                'Saint-Mathieu-du-Parc',
                'Saint-Maxime-du-Mont-Louis',
                'Saint-Médard',
                'Saint-Michel',
                'Saint-Michel-de-Bellechasse',
                'Saint-Michel-des-Saints',
                'Saint-Michel-du-Squatec',
                'Saint-Modeste',
                'Saint-Nazaire',
                'Saint-Nérée-de-Bellechasse',
                'Saint-Norbert-d\'Arthabaska',
                'Saint-Omer',
                'Saint-Pacôme',
                'Saint-Patrice-de-Beaurivage',
                'Saint-Patrice-de-Sherrington',
                'Saint-Paul',
                'Saint-Paul-d\'Abbotsford',
                'Saint-Paul-de-l\'Île-aux-Noix',
                'Saint-Paul-de-la-Croix',
                'Saint-Paul-de-Montminy',
                'Saint-Paulin',
                'Saint-Philibert',
                'Saint-Pierre-de-Broughton',
                'Saint-Pierre-de-l\'Île-d\'Orléans',
                'Saint-Pierre-de-Lamy',
                'Saint-Pierre-les-Becquets',
                'Saint-Placide',
                'Saint-Polycarpe',
                'Saint-Prime',
                'Saint-Prosper',
                'Saint-Prosper-de-Champlain',
                'Saint-Raphaël',
                'Saint-Rémi-de-Tingwick',
                'Saint-René-de-Matane',
                'Saint-Robert',
                'Saint-Robert-Bellarmin',
                'Saint-Roch-de-l\'Achigan',
                'Saint-Roch-de-Richelieu',
                'Saint-Roch-des-Aulnaies',
                'Saint-Roch-Ouest',
                'Saint-Romain',
                'Saint-Samuel',
                'Saint-Sébastien',
                'Saint-Simon',
                'Saint-Simon-de-Rimouski',
                'Saint-Simon-les-Mines',
                'Saint-Siméon',
                'Saint-Sixte',
                'Saint-Stanislas',
                'Saint-Stanislas-de-Kostka',
                'Saint-Sylvère',
                'Saint-Sylvestre',
                'Saint-Télesphore',
                'Saint-Théodore-d\'Acton',
                'Saint-Théophile',
                'Saint-Thomas',
                'Saint-Thomas-Didyme',
                'Saint-Tite-des-Caps',
                'Saint-Ubalde',
                'Saint-Ulric',
                'Saint-Urbain-Premier',
                'Saint-Valentin',
                'Saint-Valère',
                'Saint-Valérien-de-Milton',
                'Saint-Vallier',
                'Saint-Venant-de-Paquette',
                'Saint-Vianney',
                'Saint-Victor',
                'Saint-Wenceslas',
                'Saint-Zacharie',
                'Saint-Zénon',
                'Sainte-Agathe-de-Lotbinière',
                'Sainte-Angèle-de-Mérici',
                'Sainte-Angèle-de-Monnoir',
                'Sainte-Angèle-de-Prémont',
                'Sainte-Anne-de-la-Pérade',
                'Sainte-Anne-de-la-Rochelle',
                'Sainte-Anne-de-Sorel',
                'Sainte-Anne-du-Lac',
                'Sainte-Aurélie',
                'Sainte-Barbe',
                'Sainte-Béatrix',
                'Sainte-Brigide-d\'Iberville',
                'Sainte-Catherine-de-Hatley',
                'Sainte-Cécile-de-Milton',
                'Sainte-Cécile-de-Whitton',
                'Sainte-Christine-d\'Auvergne',
                'Sainte-Claire',
                'Sainte-Clotilde',
                'Sainte-Clotilde-de-Beauce',
                'Sainte-Clotilde-de-Horton',
                'Sainte-Croix',
                'Sainte-Élisabeth',
                'Sainte-Émélie-de-l\'Énergie',
                'Sainte-Eulalie',
                'Sainte-Euphémie-sur-Rivière-du-Sud',
                'Sainte-Famille-de-l\'Île-d\'Orléans',
                'Sainte-Félicité',
                'Sainte-Florence',
                'Sainte-Françoise',
                'Sainte-Geneviève-de-Berthier',
                'Sainte-Germaine-Boulé',
                'Sainte-Gertrude-Manneville',
                'Sainte-Hedwidge',
                'Sainte-Hélène-de-Bagot',
                'Sainte-Hélène-de-Chester',
                'Sainte-Hélène-de-Kamouraska',
                'Sainte-Jeanne-d\'Arc-de-la-Mitis',
                'Sainte-Julienne',
                'Sainte-Justine',
                'Sainte-Justine-de-Newton',
                'Sainte-Luce',
                'Sainte-Lucie-de-Beauregard',
                'Sainte-Lucie-des-Laurentides',
                'Sainte-Madeleine-de-la-Rivière-Madeleine',
                'Sainte-Marcelline-de-Kildare',
                'Sainte-Marguerite-Marie',
                'Sainte-Marie-de-Blandford',
                'Sainte-Marie-Salomé',
                'Sainte-Marthe',
                'Sainte-Martine',
                'Sainte-Mélanie',
                'Sainte-Monique',
                'Sainte-Paule',
                'Sainte-Perpétue',
                'Sainte-Rita',
                'Sainte-Rose-de-Watford',
                'Sainte-Sabine',
                'Sainte-Sophie',
                'Sainte-Sophie-d\'Halifax',
                'Sainte-Thècle',
                'Sainte-Thérèse-de-Gaspé',
                'Sainte-Thérèse-de-la-Gatineau',
                'Sainte-Ursule',
                'Sainte-Victoire-de-Sorel',
                'Saints-Anges',
                'Sayabec',
                'Scott',
                'Shawville',
                'Sheenboro',
                'Shigawake',
                'Stanbridge East',
                'Stanbridge Station',
                'Stanstead-Est',
                'Stoke',
                'Stornoway',
                'Taschereau',
                'Terrasse-Vaudreuil',
                'Thorne',
                'Tingwick',
                'Tourville',
                'Très-Saint-Rédempteur',
                'Trois-Rives',
                'Ulverton',
                'Upton',
                'Val-Alain',
                'Val-Brillant',
                'Val-des-Bois',
                'Val-des-Lacs',
                'Val-des-Monts',
                'Val-Joli',
                'Val-Morin',
                'Val-Racine',
                'Val-Saint-Gilles',
                'Vallée-Jonction',
                'Venise-en-Québec',
                'Verchères',
                'Villeroy',
                'La Visitation-de-l\'Île-Dupas',
                'La Visitation-de-Yamaska',
                'Waltham',
                'Weedon',
                'Wentworth-Nord',
                'West Bolton',
                'Wickham',
                'Wotton',
                'Yamachiche',
                'Yamaska',
            ],
        ],
        'villages' => [
            'display_count' => 44,
            'places' => [
                'Abercorn',
                'Ayer\'s Cliff',
                'Baie-Trinité',
                'Brome',
                'Chute-aux-Outardes',
                'Fort-Coulonge',
                'Godbout',
                'Grandes-Piles',
                'Grenville',
                'Hébertville-Station',
                'Hemmingford',
                'Kingsbury',
                'Lac-Poulin',
                'Lac-Saguay',
                'La Guadeloupe',
                'Laurier-Station',
                'Lawrenceville',
                'Marsoui',
                'Massueville',
                'Mont-Saint-Pierre',
                'North Hatley',
                'Notre-Dame-du-Bon-Conseil',
                'Ormstown',
                'Pointe-aux-Outardes',
                'Pointe-des-Cascades',
                'Pointe-Fortune',
                'Pointe-Lebel',
                'Portage-du-Fort',
                'Price',
                'Roxton Falls',
                'Saint-André-du-Lac-Saint-Jean',
                'Saint-Célestin',
                'Saint-Noël',
                'Saint-Pierre',
                'Sainte-Jeanne-d\'Arc',
                'Sainte-Madeleine',
                'Sainte-Pétronille',
                'Senneville',
                'Stukely-Sud',
                'Tadoussac',
                'Tring-Jonction',
                'Val-David',
                'Vaudreuil-sur-le-Lac',
                'Warden',
            ],
        ],
        'district_wide' => [
            'display_count' => 87,
            'places' => [
                'Abitibi',
                'Abitibi-Ouest',
                'Acton',
                'Antoine-Labelle',
                'Argenteuil',
                'Arthabaska',
                'Avignon',
                'Beauce-Centre',
                'Beauce-Sartigan',
                'Beauharnois-Salaberry',
                'Bécancour',
                'Bellechasse',
                'Bonaventure',
                'Brome-Missisquoi',
                'Caniapiscau',
                'Charlevoix',
                'Charlevoix-Est',
                'Coaticook',
                'D\'Autray',
                'Deux-Montagnes',
                'Drummond',
                'Joliette',
                'Kamouraska',
                'L\'Assomption',
                'L\'Érable',
                'L\'Île-d\'Orléans',
                'L\'Islet',
                'La Côte-de-Beaupré',
                'La Côte-de-Gaspé',
                'La Haute-Côte-Nord',
                'La Haute-Gaspésie',
                'La Haute-Yamaska',
                'La Jacques-Cartier',
                'La Matanie',
                'La Matapédia',
                'La Mitis',
                'La Nouvelle-Beauce',
                'La Rivière-du-Nord',
                'La Vallée-de-la-Gatineau',
                'La Vallée-de-l\'Or',
                'La Vallée-du-Richelieu',
                'Lac-Saint-Jean-Est',
                'Le Domaine-du-Roy',
                'Le Fjord-du-Saguenay',
                'Le Golfe-du-Saint-Laurent',
                'Le Granit',
                'Le Haut-Richelieu',
                'Le Haut-Saint-François',
                'Le Haut-Saint-Laurent',
                'Le Rocher-Percé',
                'Le Val-Saint-François',
                'Les Appalaches',
                'Les Basques',
                'Les Chenaux',
                'Les Collines-de-l\'Outaouais',
                'Les Etchemins',
                'Les Jardins-de-Napierville',
                'Les Laurentides',
                'Les Maskoutains',
                'Les Moulins',
                'Les Pays-d\'en-Haut',
                'Les Sources',
                'Lotbinière',
                'Manicouagan',
                'Marguerite-D\'Youville',
                'Maria-Chapdelaine',
                'Maskinongé',
                'Matawinie',
                'Mékinac',
                'Memphrémagog',
                'Minganie',
                'Montcalm',
                'Montmagny',
                'Nicolet-Yamaska',
                'Papineau',
                'Pierre-De Saurel',
                'Pontiac',
                'Portneuf',
                'Rimouski-Neigette',
                'Rivière-du-Loup',
                'Roussillon',
                'Rouville',
                'Sept-Rivières',
                'Témiscamingue',
                'Témiscouata',
                'Thérèse-De Blainville',
                'Vaudreuil-Soulanges',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 31,
        ],
    ],
];
