<?php

return [
    'Saskatchewan' => [
        'city_wide' => [
            'display_count' => 16,
            'places' => [
                'Estevan',
                'Humboldt',
                'Lloydminster',
                'Martensville',
                'Meadow Lake',
                'Melfort',
                'Melville',
                'Moose Jaw',
                'North Battleford',
                'Prince Albert',
                'Regina',
                'Saskatoon',
                'Swift Current',
                'Warman',
                'Weyburn',
                'Yorkton',
            ],
        ],
        'towns' => [
            'display_count' => 147,
            'places' => [
                'Aberdeen',
                'Alameda',
                'Allan',
                'Arborfield',
                'Arcola',
                'Asquith',
                'Assiniboia',
                'Balcarres',
                'Balgonie',
                'Battleford',
                'Bengough',
                'Bienfait',
                'Big River',
                'Biggar',
                'Birch Hills',
                'Blaine Lake',
                'Bredenbury',
                'Broadview',
                'Bruno',
                'Burstall',
                'Cabri',
                'Canora',
                'Carlyle',
                'Carnduff',
                'Carrot River',
                'Central Butte',
                'Choiceland',
                'Churchbridge',
                'Colonsay',
                'Coronach',
                'Craik',
                'Cudworth',
                'Cupar',
                'Cut Knife',
                'Dalmeny',
                'Davidson',
                'Delisle',
                'Duck Lake',
                'Dundurn',
                'Eastend',
                'Eatonia',
                'Elrose',
                'Esterhazy',
                'Eston',
                'Fleming',
                'Foam Lake',
                'Fort Qu\'Appelle',
                'Francis',
                'Govan',
                'Grand Coulee',
                'Gravelbourg',
                'Grenfell',
                'Gull Lake',
                'Hafford',
                'Hague',
                'Hanley',
                'Hepburn',
                'Herbert',
                'Hudson Bay',
                'Imperial',
                'Indian Head',
                'Ituna',
                'Kamsack',
                'Kelvington',
                'Kerrobert',
                'Kindersley',
                'Kinistino',
                'Kipling',
                'Kyle',
                'Lafleche',
                'Lampman',
                'Langenburg',
                'Langham',
                'Lanigan',
                'Lashburn',
                'Leader',
                'Lemberg',
                'Leroy',
                'Lumsden',
                'Luseland',
                'Macklin',
                'Maidstone',
                'Maple Creek',
                'Marshall',
                'Midale',
                'Milestone',
                'Moosomin',
                'Morse',
                'Mossbank',
                'Naicam',
                'Nipawin',
                'Nokomis',
                'Norquay',
                'Ogema',
                'Osler',
                'Outlook',
                'Oxbow',
                'Pense',
                'Pilot Butte',
                'Ponteix',
                'Porcupine Plain',
                'Preeceville',
                'Qu\'Appelle',
                'Radisson',
                'Radville',
                'Raymore',
                'Redvers',
                'Regina Beach',
                'Rocanville',
                'Rockglen',
                'Rose Valley',
                'Rosetown',
                'Rosthern',
                'Rouleau',
                'Saltcoats',
                'Scott',
                'Shaunavon',
                'Shellbrook',
                'Sintaluta',
                'Southey',
                'Spiritwood',
                'Springside',
                'St. Brieux',
                'St. Walburg',
                'Star City',
                'Stoughton',
                'Strasbourg',
                'Sturgis',
                'Tisdale',
                'Turtleford',
                'Unity',
                'Vonda',
                'Wadena',
                'Wakaw',
                'Waldheim',
                'Wapella',
                'Watrous',
                'Watson',
                'Wawota',
                'White City',
                'Whitewood',
                'Wilkie',
                'Willow Bunch',
                'Wolseley',
                'Wynyard',
                'Yellow Grass',
                'Zealandia',
            ],
        ],
        'villages' => [
            'display_count' => 309,
            'places' => [
                // Villages (258) + Northern villages (11) + Resort villages (40)
                'Abbey',
                'Abernethy',
                'Air Ronge',
                'Albertville',
                'Alice Beach',
                'Alida',
                'Alvena',
                'Annaheim',
                'Aquadeo',
                'Archerwill',
                'Arran',
                'Atwater',
                'Avonlea',
                'Aylesbury',
                'Aylsham',
                'Bangor',
                'Beatty',
                'Beauval',
                'Beaver Flat',
                'Beechy',
                'Belle Plaine',
                'Bethune',
                'Big Shell',
                'Bird\'s Point',
                'Bjorkdale',
                'Bladworth',
                'Borden',
                'Bracken',
                'Bradwell',
                'Briercrest',
                'Brock',
                'Broderick',
                'Brownlee',
                'B-Say-Tah',
                'Buchanan',
                'Buena Vista',
                'Buffalo Narrows',
                'Bulyea',
                'Cadillac',
                'Calder',
                'Candle Lake',
                'Canwood',
                'Carievale',
                'Carmichael',
                'Caronport',
                'Ceylon',
                'Chamberlain',
                'Chaplin',
                'Chitek Lake',
                'Chorney Beach',
                'Christopher Lake',
                'Clavet',
                'Climax',
                'Cochin',
                'Coderre',
                'Codette',
                'Coleville',
                'Conquest',
                'Consul',
                'Coteau Beach',
                'Craven',
                'Creelman',
                'Cumberland House',
                'Dafoe',
                'Debden',
                'Denholm',
                'Denare Beach',
                'Denzil',
                'Dilke',
                'Dinsmore',
                'Disley',
                'District of Katepwa',
                'Dodsland',
                'Dorintosh',
                'Drake',
                'Drinkwater',
                'Dubuc',
                'Duff',
                'Duval',
                'Dysart',
                'Earl Grey',
                'Ebenezer',
                'Echo Bay',
                'Edam',
                'Edenwold',
                'Elbow',
                'Elfros',
                'Endeavour',
                'Englefeld',
                'Ernfold',
                'Etters Beach',
                'Eyebrow',
                'Fairlight',
                'Fenwood',
                'Fillmore',
                'Findlater',
                'Flaxcombe',
                'Forget',
                'Fort San',
                'Fosston',
                'Fox Valley',
                'Frobisher',
                'Frontier',
                'Gainsborough',
                'Gerald',
                'Glaslyn',
                'Glen Ewen',
                'Glen Harbour',
                'Glenavon',
                'Glenside',
                'Golden Prairie',
                'Goodeve',
                'Goodsoil',
                'Goodwater',
                'Grand Coulee',
                'Grandview Beach',
                'Grayson',
                'Green Lake',
                'Greig Lake',
                'Halbrite',
                'Harris',
                'Hawarden',
                'Hazenmore',
                'Hazlet',
                'Heward',
                'Hodgeville',
                'Holdfast',
                'Hubbard',
                'Hyas',
                'Ile-a-la-Crosse',
                'Invermay',
                'Island View',
                'Jansen',
                'Kannata Valley',
                'Keeler',
                'Kelliher',
                'Kenaston',
                'Kendal',
                'Kennedy',
                'Kenosee Lake',
                'Killaly',
                'Kincaid',
                'Kinley',
                'Kisbey',
                'Kivimaa-Moonlight Bay',
                'Krydor',
                'La Loche',
                'Laird',
                'Lake Alma',
                'Lake Lenore',
                'Lancer',
                'Landis',
                'Lang',
                'Leask',
                'Lebret',
                'Leoville',
                'Leross',
                'Leslie Beach',
                'Lestock',
                'Liberty',
                'Limerick',
                'Lintlaw',
                'Lipton',
                'Loon Lake',
                'Loreburn',
                'Love',
                'Lucky Lake',
                'Lumsden Beach',
                'Macnutt',
                'Macoun',
                'Macrorie',
                'Major',
                'Makwa',
                'Mankota',
                'Manitou Beach',
                'Manor',
                'Marcelin',
                'Marengo',
                'Margo',
                'Markinch',
                'Marquis',
                'Marsden',
                'Maryfield',
                'Maymont',
                'McLean',
                'McTaggart',
                'Meacham',
                'Meath Park',
                'Medstead',
                'Melville Beach',
                'Mendham',
                'Meota',
                'Mervin',
                'Metinota',
                'Middle Lake',
                'Milden',
                'Minton',
                'Mistatim',
                'Mistusinne',
                'Montmartre',
                'Mortlach',
                'Muenster',
                'Neilburg',
                'Netherhill',
                'Neudorf',
                'Neville',
                'North Grove',
                'North Portal',
                'Odessa',
                'Osage',
                'Paddockwood',
                'Pangman',
                'Paradise Hill',
                'Parkside',
                'Paynton',
                'Pebble Baye',
                'Pelican Narrows',
                'Pelican Pointe',
                'Pelly',
                'Pennant',
                'Perdue',
                'Pierceland',
                'Pilger',
                'Pinehouse',
                'Pleasantdale',
                'Plenty',
                'Plunkett',
                'Prelate',
                'Primate',
                'Prud\'homme',
                'Punnichy',
                'Quill Lake',
                'Quinton',
                'Rama',
                'Rhein',
                'Richard',
                'Richmound',
                'Ridgedale',
                'Riverhurst',
                'Roche Percee',
                'Ruddell',
                'Rush Lake',
                'Sandy Bay',
                'Saskatchewan Beach',
                'Sceptre',
                'Sedley',
                'Semans',
                'Senlac',
                'Shamrock',
                'Sheho',
                'Shell Lake',
                'Shields',
                'Silton',
                'Simpson',
                'Smeaton',
                'Smiley',
                'South Lake',
                'Spalding',
                'Speers',
                'Spy Hill',
                'St. Benedict',
                'St. Gregor',
                'St. Louis',
                'Stenen',
                'Stewart Valley',
                'Stockholm',
                'Storthoaks',
                'Strongfield',
                'Success',
                'Sun Valley',
                'Sunset Cove',
                'Tantallon',
                'Tessier',
                'Theodore',
                'Thode',
                'Tobin Lake',
                'Togo',
                'Tompkins',
                'Torquay',
                'Tramping Lake',
                'Tribune',
                'Tugaske',
                'Tuxford',
                'Val Marie',
                'Valparaiso',
                'Vanguard',
                'Vanscoy',
                'Vibank',
                'Viscount',
                'Wakaw Lake',
                'Waldeck',
                'Waldron',
                'Waseca',
                'Webb',
                'Wee Too Beach',
                'Weekes',
                'Weirdale',
                'Weldon',
                'Welwyn',
                'West End',
                'White Fox',
                'Wilcox',
                'Windthorst',
                'Wiseton',
                'Wood Mountain',
                'Yarbo',
                'Young',
                'Zelma',
                'Zenon Park',
            ],
        ],
        'municipalities' => [
            'display_count' => 296,
            'places' => [
                'RM of Aberdeen No. 373',
                'RM of Abernethy No. 186',
                'RM of Antelope Park No. 322',
                'RM of Antler No. 61',
                'RM of Arborfield No. 456',
                'RM of Argyle No. 1',
                'RM of Arlington No. 79',
                'RM of Arm River No. 252',
                'RM of Auvergne No. 76',
                'RM of Baildon No. 131',
                'RM of Barrier Valley No. 397',
                'RM of Battle River No. 438',
                'RM of Bayne No. 371',
                'RM of Beaver River No. 622',
                'RM of Bengough No. 40',
                'RM of Benson No. 35',
                'RM of Big Arm No. 251',
                'RM of Big Quill No. 308',
                'RM of Big River No. 555',
                'RM of Big Stick No. 141',
                'RM of Biggar No. 347',
                'RM of Birch Hills No. 460',
                'RM of Bjorkdale No. 426',
                'RM of Blaine Lake No. 434',
                'RM of Blucher No. 343',
                'RM of Bone Creek No. 108',
                'RM of Bratt\'s Lake No. 129',
                'RM of Britannia No. 502',
                'RM of Brock No. 64',
                'RM of Brokenshell No. 68',
                'RM of Browning No. 34',
                'RM of Buchanan No. 304',
                'RM of Buckland No. 491',
                'RM of Buffalo No. 409',
                'RM of Calder No. 241',
                'RM of Caledonia No. 99',
                'RM of Cambria No. 6',
                'RM of Cana No. 214',
                'RM of Canaan No. 225',
                'RM of Canwood No. 494',
                'RM of Carmichael No. 109',
                'RM of Caron No. 162',
                'RM of Chaplin No. 164',
                'RM of Chester No. 125',
                'RM of Chesterfield No. 261',
                'RM of Churchbridge No. 211',
                'RM of Clayton No. 333',
                'RM of Clinworth No. 230',
                'RM of Coalfields No. 4',
                'RM of Colonsay No. 342',
                'RM of Connaught No. 457',
                'RM of Corman Park No. 344',
                'RM of Cote No. 271',
                'RM of Coteau No. 255',
                'RM of Coulee No. 136',
                'RM of Craik No. 222',
                'RM of Cupar No. 218',
                'RM of Cut Knife No. 439',
                'RM of Cymri No. 36',
                'RM of Deer Forks No. 232',
                'RM of District of Lakeland No. 521',
                'RM of Douglas No. 436',
                'RM of Duck Lake No. 463',
                'RM of Dufferin No. 190',
                'RM of Dundurn No. 314',
                'RM of Eagle Creek No. 376',
                'RM of Edenwold No. 158',
                'RM of Elcapo No. 154',
                'RM of Eldon No. 471',
                'RM of Elfros No. 307',
                'RM of Elmsthorpe No. 100',
                'RM of Emerald No. 277',
                'RM of Enfield No. 194',
                'RM of Enniskillen No. 3',
                'RM of Enterprise No. 142',
                'RM of Estevan No. 5',
                'RM of Excel No. 71',
                'RM of Excelsior No. 166',
                'RM of Eye Hill No. 382',
                'RM of Eyebrow No. 193',
                'RM of Fertile Belt No. 183',
                'RM of Fertile Valley No. 285',
                'RM of Fillmore No. 96',
                'RM of Fish Creek No. 402',
                'RM of Flett\'s Springs No. 429',
                'RM of Foam Lake No. 276',
                'RM of Fox Valley No. 171',
                'RM of Francis No. 127',
                'RM of Frenchman Butte No. 501',
                'RM of Frontier No. 19',
                'RM of Garden River No. 490',
                'RM of Garry No. 245',
                'RM of Glen Bain No. 105',
                'RM of Glen McPherson No. 46',
                'RM of Glenside No. 377',
                'RM of Golden West No. 95',
                'RM of Good Lake No. 274',
                'RM of Grandview No. 349',
                'RM of Grant No. 372',
                'RM of Grass Lake No. 381',
                'RM of Grassy Creek No. 78',
                'RM of Gravelbourg No. 104',
                'RM of Grayson No. 184',
                'RM of Great Bend No. 405',
                'RM of Griffin No. 66',
                'RM of Gull Lake No. 139',
                'RM of Happy Valley No. 10',
                'RM of Happyland No. 231',
                'RM of Harris No. 316',
                'RM of Hart Butte No. 11',
                'RM of Hazel Dell No. 335',
                'RM of Hazelwood No. 94',
                'RM of Heart\'s Hill No. 352',
                'RM of Hillsborough No. 132',
                'RM of Hillsdale No. 440',
                'RM of Hoodoo No. 401',
                'RM of Hudson Bay No. 394',
                'RM of Humboldt No. 370',
                'RM of Huron No. 223',
                'RM of Indian Head No. 156',
                'RM of Insinger No. 275',
                'RM of Invergordon No. 430',
                'RM of Invermay No. 305',
                'RM of Ituna Bon Accord No. 246',
                'RM of Kellross No. 247',
                'RM of Kelvington No. 366',
                'RM of Key West No. 70',
                'RM of Keys No. 303',
                'RM of Kindersley No. 290',
                'RM of King George No. 256',
                'RM of Kingsley No. 124',
                'RM of Kinistino No. 459',
                'RM of Lac Pelletier No. 107',
                'RM of Lacadena No. 228',
                'RM of Laird No. 404',
                'RM of Lajord No. 128',
                'RM of Lake Alma No. 8',
                'RM of Lake Johnston No. 102',
                'RM of Lake Lenore No. 399',
                'RM of Lake of the Rivers No. 72',
                'RM of Lakeside No. 338',
                'RM of Lakeview No. 337',
                'RM of Langenburg No. 181',
                'RM of Last Mountain Valley No. 250',
                'RM of Laurier No. 38',
                'RM of Lawtonia No. 135',
                'RM of Leask No. 464',
                'RM of Leroy No. 339',
                'RM of Lipton No. 217',
                'RM of Livingston No. 331',
                'RM of Lomond No. 37',
                'RM of Lone Tree No. 18',
                'RM of Longlaketon No. 219',
                'RM of Loon Lake No. 561',
                'RM of Loreburn No. 254',
                'RM of Lost River No. 313',
                'RM of Lumsden No. 189',
                'RM of Manitou Lake No. 442',
                'RM of Mankota No. 45',
                'RM of Maple Bush No. 224',
                'RM of Maple Creek No. 111',
                'RM of Mariposa No. 350',
                'RM of Marquis No. 191',
                'RM of Marriott No. 317',
                'RM of Martin No. 122',
                'RM of Maryfield No. 91',
                'RM of Mayfield No. 406',
                'RM of McCraney No. 282',
                'RM of McKillop No. 220',
                'RM of McLeod No. 185',
                'RM of Meadow Lake No. 588',
                'RM of Medstead No. 497',
                'RM of Meeting Lake No. 466',
                'RM of Meota No. 468',
                'RM of Mervin No. 499',
                'RM of Milden No. 286',
                'RM of Milton No. 292',
                'RM of Miry Creek No. 229',
                'RM of Monet No. 257',
                'RM of Montmartre No. 126',
                'RM of Montrose No. 315',
                'RM of Moose Creek No. 33',
                'RM of Moose Jaw No. 161',
                'RM of Moose Mountain No. 63',
                'RM of Moose Range No. 486',
                'RM of Moosomin No. 121',
                'RM of Morris No. 312',
                'RM of Morse No. 165',
                'RM of Mount Hope No. 279',
                'RM of Mount Pleasant No. 2',
                'RM of Mountain View No. 318',
                'RM of Newcombe No. 260',
                'RM of Nipawin No. 487',
                'RM of North Battleford No. 437',
                'RM of North Qu\'Appelle No. 187',
                'RM of Norton No. 69',
                'RM of Oakdale No. 320',
                'RM of Old Post No. 43',
                'RM of Orkney No. 244',
                'RM of Paddockwood No. 520',
                'RM of Parkdale No. 498',
                'RM of Paynton No. 470',
                'RM of Pense No. 160',
                'RM of Perdue No. 346',
                'RM of Piapot No. 110',
                'RM of Pinto Creek No. 75',
                'RM of Pittville No. 169',
                'RM of Pleasant Valley No. 288',
                'RM of Pleasantdale No. 398',
                'RM of Ponass Lake No. 367',
                'RM of Poplar Valley No. 12',
                'RM of Porcupine No. 395',
                'RM of Prairie Rose No. 309',
                'RM of Prairiedale No. 321',
                'RM of Preeceville No. 334',
                'RM of Prince Albert No. 461',
                'RM of Progress No. 351',
                'RM of Reciprocity No. 32',
                'RM of Redberry No. 435',
                'RM of Redburn No. 130',
                'RM of Reford No. 379',
                'RM of Reno No. 51',
                'RM of Riverside No. 168',
                'RM of Rocanville No. 151',
                'RM of Rodgers No. 133',
                'RM of Rosedale No. 283',
                'RM of Rosemount No. 378',
                'RM of Rosthern No. 403',
                'RM of Round Hill No. 467',
                'RM of Round Valley No. 410',
                'RM of Rudy No. 284',
                'RM of Saltcoats No. 213',
                'RM of Sarnia No. 221',
                'RM of Saskatchewan Landing No. 167',
                'RM of Sasman No. 336',
                'RM of Scott No. 98',
                'RM of Senlac No. 411',
                'RM of Shamrock No. 134',
                'RM of Shellbrook No. 493',
                'RM of Sherwood No. 159',
                'RM of Silverwood No. 123',
                'RM of Sliding Hills No. 273',
                'RM of Snipe Lake No. 259',
                'RM of Souris Valley No. 7',
                'RM of South Qu\'Appelle No. 157',
                'RM of Spalding No. 368',
                'RM of Spiritwood No. 496',
                'RM of Spy Hill No. 152',
                'RM of St. Andrews No. 287',
                'RM of St. Louis No. 431',
                'RM of St. Peter No. 369',
                'RM of St. Philips No. 301',
                'RM of Stanley No. 215',
                'RM of Star City No. 428',
                'RM of Stonehenge No. 73',
                'RM of Storthoaks No. 31',
                'RM of Surprise Valley No. 9',
                'RM of Sutton No. 103',
                'RM of Swift Current No. 137',
                'RM of Tecumseh No. 65',
                'RM of Terrell No. 101',
                'RM of The Gap No. 39',
                'RM of Three Lakes No. 400',
                'RM of Tisdale No. 427',
                'RM of Torch River No. 488',
                'RM of Touchwood No. 248',
                'RM of Tramping Lake No. 380',
                'RM of Tullymet No. 216',
                'RM of Turtle River No. 469',
                'RM of Usborne No. 310',
                'RM of Val Marie No. 17',
                'RM of Vanscoy No. 345',
                'RM of Victory No. 226',
                'RM of Viscount No. 341',
                'RM of Wallace No. 243',
                'RM of Walpole No. 92',
                'RM of Waverley No. 44',
                'RM of Wawken No. 93',
                'RM of Webb No. 138',
                'RM of Wellington No. 97',
                'RM of Weyburn No. 67',
                'RM of Wheatlands No. 163',
                'RM of Whiska Creek No. 106',
                'RM of White Valley No. 49',
                'RM of Willner No. 253',
                'RM of Willow Bunch No. 42',
                'RM of Willow Creek No. 458',
                'RM of Willowdale No. 153',
                'RM of Wilton No. 472',
                'RM of Winslow No. 319',
                'RM of Wise Creek No. 77',
                'RM of Wolseley No. 155',
                'RM of Wolverine No. 340',
                'RM of Wood Creek No. 281',
                'RM of Wood River No. 74',
                'RM of Wreford No. 280',
            ],
        ],
        'district_wide' => [
            'display_count' => 18,
            'places' => [
                'Division No. 1',
                'Division No. 2',
                'Division No. 3',
                'Division No. 4',
                'Division No. 5',
                'Division No. 6',
                'Division No. 7',
                'Division No. 8',
                'Division No. 9',
                'Division No. 10',
                'Division No. 11',
                'Division No. 12',
                'Division No. 13',
                'Division No. 14',
                'Division No. 15',
                'Division No. 16',
                'Division No. 17',
                'Division No. 18',
            ],
        ],
        'indian_reserves' => [
            'display_count' => 782,
        ],
    ],
];
