<?php

/*
|--------------------------------------------------------------------------
| Start Advertising questionnaire data
|--------------------------------------------------------------------------
|
| Reference data driving the advertiser "Start Advertising" wizard.
|
| Province-specific place lists live under `province_region_categories`.
| Add the same structure for any province that needs deeper local targeting.
|
*/

return [

    // Minimum commitment shown on the acceptance gate.
    'min_commitment_notice' => 'As of now we are not accepting any advertisements for less than a month.',

    'industries' => [
        'Agriculture',
        'Forestry',
        'Fishing & Hunting',
        'Mining',
        'Oil & Gas',
        'Utilities (Electric, Water, Gas)',
        'Construction',
        'Manufacturing',
        'Wholesale Trade',
        'Retail Trade',
        'Transportation & Logistics',
        'Warehousing',
        'Information Technology',
        'Telecommunications',
        'Media & Entertainment',
        'Finance & Insurance',
        'Real Estate',
        'Rental & Leasing Services',
        'Professional Services',
        'Legal Services',
        'Accounting & Bookkeeping',
        'Engineering & Architecture',
        'Scientific Research & Development',
        'Management Consulting',
        'Administrative & Support Services',
        'Waste Management & Remediation',
        'Educational Services',
        'Healthcare & Social Assistance',
        'Hospitals & Clinics',
        'Pharmaceuticals & Biotechnology',
        'Arts, Entertainment & Recreation',
        'Hotels & Accommodation',
        'Food Services & Drinking Places',
        'Public Administration & Government',
        'Non-profit Organizations',
        'Defense & Aerospace',
        'Automotive',
        'Apparel & Textiles',
        'Chemical',
        'Consumer Goods',
        'E-commerce',
        'Environmental Services',
        'Event Planning & Services',
        'Human Resources & Staffing',
        'Import & Export',
        'Interior Design',
        'Jewellery & Watches',
        'Logistics & Supply Chain',
        'Marketing & Advertising',
        'Mechanical or Industrial Engineering',
        'Petroleum & Coal Products',
        'Printing & Publishing',
        'Renewable Energy',
        'Security & Investigations',
        'Sports & Recreation',
        'Travel & Tourism',
        'Utilities',
        'Venture Capital & Private Equity',
        'Veterinary Services',
        'Web Development & Design',
        'Wine & Spirits',
        'Cannabis',
        'Cryptocurrency & Blockchain',
        'Gaming (Video Games, eSports)',
        'Freight & Shipping',
        'Tattoo & Body Art',
        'Repair & Maintenance',
        'Childcare Services',
        'Beauty & Personal Care',
    ],

    // Canadian provinces & territories (used for business location + targeting).
    'provinces' => [
        'Alberta',
        'British Columbia',
        'Manitoba',
        'New Brunswick',
        'Newfoundland and Labrador',
        'Nova Scotia',
        'Ontario',
        'Prince Edward Island',
        'Quebec',
        'Saskatchewan',
        'Northwest Territories',
        'Nunavut',
        'Yukon',
    ],

    // Special targeting option offered alongside the provinces.
    'country_wide_label' => 'Country wide',

    /*
    | Region categories that appear once a province is targeted. Common
    | category definitions are kept here, and province-specific place lists
    | can be supplied in province_region_categories below.
    */
    'region_categories' => [
        'across_province' => [
            'label' => 'Across the Province',
            'places' => [],
        ],
        'city_wide' => [
            'label' => 'City wide',
            'places' => [],
        ],
        'municipalities' => [
            'label' => 'Municipalities and Rural Municipalities',
            'places' => [],
        ],
        'towns' => [
            'label' => 'Towns & Townships',
            'places' => [],
        ],
        'district_wide' => [
            'label' => 'District wide',
            'places' => [],
        ],
        'villages' => [
            'label' => 'Villages',
            'places' => [],
        ],
        'indian_reserves' => [
            'label' => 'Indian Reserves',
            'places' => [],
        ],
    ],

    // Manitoba is defined inline below; all other provinces/territories are
    // merged in from config/regions/<province>.php (one file per province).
    'province_region_categories' => array_merge([
        'Manitoba' => [
            'city_wide' => [
                'places' => [
                    'Brandon',
                    'Dauphin',
                    'Flin Flon',
                    'Morden',
                    'Portage la Prairie',
                    'Selkirk',
                    'Steinbach',
                    'Thompson',
                    'Winkler',
                    'Winnipeg',
                ],
            ],
            'municipalities' => [
                'display_count' => 99,
                'places' => [
                    'Alexander',
                    'Alonsa',
                    'Argyle',
                    'Armstrong',
                    'Bifrost - Riverton',
                    'Boissevain - Morton',
                    'Brenda - Waskada',
                    'Brokenhead',
                    'Cartier',
                    'Cartwright-Roblin',
                    'Clanwilliam - Erickson',
                    'Coldwell',
                    'Cornwallis',
                    'Dauphin',
                    'De Salaberry',
                    'Deloraine - Winchester',
                    'Dufferin',
                    'East St. Paul',
                    'Ellice - Archie',
                    'Emerson - Franklin',
                    'Ethelbert',
                    'Fisher',
                    'Gilbert Plains',
                    'Gimli',
                    'Glenboro - South Cypress',
                    'Glenella - Lansdowne',
                    'Grahamdale',
                    'Grandview',
                    'Grassland',
                    'Grey',
                    'Hamiota',
                    'Hanover',
                    'Harrison Park',
                    'Headingley',
                    'Kelsey',
                    'Killarney - Turtle Mountain',
                    'La Broquerie',
                    'Lac du Bonnet',
                    'Lakeshore',
                    'Lorne',
                    'Louise',
                    'Macdonald',
                    'McCreary',
                    'Minitonas - Bowsman',
                    'Montcalm',
                    'Morris',
                    'Mossey River',
                    'Mountain (North)',
                    'Mountain (South)',
                    'Minto-Odanah',
                    'Norfolk - Treherne',
                    'North Cypress - Langford',
                    'North Norfolk',
                    'Oakland - Wawanesa',
                    'Oakview',
                    'Pembina',
                    'Piney',
                    'Pipestone',
                    'Portage la Prairie',
                    'Prairie Lakes',
                    'Prairie View',
                    'Reynolds',
                    'Rhineland',
                    'Riding Mountain West',
                    'Ritchot',
                    'Riverdale',
                    'Roblin',
                    'Rockwood',
                    'Roland',
                    'Rosedale',
                    'Rosser',
                    'Rossburn',
                    'Russell - Binscarth',
                    'Sifton',
                    'Souris - Glenwood',
                    'Springfield',
                    'St. Andrews',
                    'St. Clements',
                    'St. François Xavier',
                    'St. Laurent',
                    'Stanley',
                    'Ste. Anne',
                    'Ste. Rose',
                    'Stuartburn',
                    'Swan Valley West',
                    'Taché',
                    'Thompson',
                    'Two Borders',
                    'Victoria',
                    'Victoria Beach',
                    'Wallace - Woodworth',
                    'West Interlake',
                    'West St. Paul',
                    'WestLake - Gladstone',
                    'Whitehead',
                    'Whitemouth',
                    'Woodlands',
                    'Yellowhead',
                ],
            ],
            'towns' => [
                'display_count' => 25,
                'places' => [
                    'Altona',
                    'Arborg',
                    'Beausejour',
                    'Carberry',
                    'Carman',
                    'Churchill',
                    'Gillam',
                    'Grand Rapids',
                    'Lac du Bonnet',
                    'Leaf Rapids',
                    'Lynn Lake',
                    'Melita',
                    'Minnedosa',
                    'Morris',
                    'Neepawa',
                    'Niverville',
                    'Powerview-Pine Falls',
                    'Snow Lake',
                    'Ste. Anne',
                    'Stonewall',
                    'Swan River',
                    'Teulon',
                    'The Pas',
                    'Virden',
                    'Winnipeg Beach',
                ],
            ],
            'district_wide' => [
                'places' => [
                    'Division No. 1',
                    'Division No. 2',
                    'Division No. 3',
                    'Division No. 4',
                    'Division No. 5',
                    'Division No. 6',
                    'Division No. 7',
                    'Division No. 8',
                    'Division No. 9',
                    'Division No. 10',
                    'Division No. 11',
                    'Division No. 12',
                    'Division No. 13',
                    'Division No. 14',
                    'Division No. 15',
                    'Division No. 16',
                    'Division No. 17',
                    'Division No. 18',
                    'Division No. 19',
                    'Division No. 20',
                    'Division No. 21',
                    'Division No. 22',
                    'Division No. 23',
                ],
            ],
            'villages' => [
                'display_count' => 2,
                'places' => [
                    'Dunnottar',
                    'St-Pierre-Jolys',
                ],
            ],
            'indian_reserves' => [
                'display_count' => 87,
                'places' => [
                    'A Kwis Ki Mahka',
                    'Berens River 13',
                    'Birdtail Creek 57',
                    'Black River 9',
                    'Black Sturgeon',
                    'Bloodvein 12',
                    'Brochet 197',
                    'Brokenhead 4',
                    'Buffalo Point 36',
                    'Canupawakpa Dakota First Nation (Oak Lake 59)',
                    'Chemawawin 2',
                    'Chemawawin 3',
                    'Churchill 1',
                    'Crane River 51',
                    'Cross Lake 19',
                    'Cross Lake 19A',
                    'Cross Lake 19E',
                    'Dakota Plains 6A',
                    'Dakota Tipi 1',
                    'Dauphin River 48A',
                    'Dog Creek 46',
                    'Ebb and Flow 52',
                    'Fairford 50',
                    'Fisher River 44',
                    'Fisher River 44A',
                    'Fort Alexander 3',
                    'Fox Lake 2',
                    'Gambler 63',
                    'Garden Hill First Nation',
                    'God\'s Lake 23',
                    'God\'s River 86A',
                    'Grand Rapids 33',
                    'Hole or Hollow Water 10',
                    'Jackhead 43',
                    'Keeseekoowenin 61',
                    'Lac Brochet 197A',
                    'Little Grand Rapids 14',
                    'Little Saskatchewan 48',
                    'Long Plain',
                    'Long Plain 6',
                    'Moose Lake 31A',
                    'Moose Lake 31D',
                    'Moose Lake 31G',
                    'Mooseocoot',
                    'Mooseocoot 4',
                    'Nelson House 170',
                    'Norway House 17',
                    'O-Pipon-Na-Piwin Cree Nation 1',
                    'Obushkudayang',
                    'Opaskwayak Cree Nation 21A',
                    'Opaskwayak Cree Nation 21B',
                    'Opaskwayak Cree Nation 21C',
                    'Opaskwayak Cree Nation 21D',
                    'Opaskwayak Cree Nation 21E',
                    'Opaskwayak Cree Nation 21I',
                    'Opaskwayak Cree Nation 21N',
                    'Oxford House 24',
                    'Pauingassi First Nation',
                    'Peguis 1B',
                    'Pine Creek 66A',
                    'Poplar River 16',
                    'Pukatawagan 198',
                    'Red Sucker Lake 1976',
                    'Red Sucker Lake 1976A',
                    'Rolling River 67',
                    'Rolling River 67B',
                    'Roseau Rapids 2A',
                    'Roseau River 2',
                    'Sandy Bay 5',
                    'Shamattawa 1',
                    'Shoal Lake (Part) 40',
                    'Shoal River 65A',
                    'Shoal River 65B',
                    'Sioux Valley Dakota Nation',
                    'Split Lake 171',
                    'St. Theresa Point',
                    'Swan Lake 7',
                    'Swan Lake 7A',
                    'Swan Lake 65C',
                    'The Narrows 49',
                    'Valley River 63A',
                    'Wasagamack',
                    'Waterhen 45',
                    'Waywayseecappo First Nation',
                    'Waywayseecappo Highway 10',
                    'Wuskwi Sipihk First Nation 2',
                    'York Landing',
                ],
            ],
        ],
    ], ...array_map(fn ($f) => require $f, glob(__DIR__.'/regions/*.php'))),

    'company_sizes' => [
        'micro' => 'Micro — 1-4 employees',
        'small' => 'Small — 5-99 employees',
        'medium' => 'Medium — 100-499 employees',
        'large' => 'Large — 500+ employees',
    ],

    'durations' => [
        '1-3' => '1-3 months',
        '3-6' => '3-6 months',
        '6-9' => '6-9 months',
        '1-year' => '1 year',
    ],

    'ad_about' => [
        'brand' => 'My brand',
        'product' => 'Promote a particular product',
        'hiring' => 'Hiring for employees',
        'message' => 'Message',
        'product_recall' => 'Product Recall',
        'others' => 'Others',
    ],

    'display_schedules' => [
        '8hrs' => '8 hrs (Regular Business hrs) 8:00 AM till 4:00 PM',
        '24hrs' => '24 hrs',
        'weekdays_business' => 'Weekdays & during business hrs',
        'weekdays_24' => 'Weekdays & 24 hrs',
        'weekends_24' => 'Weekends - 24 hrs',
        'all_days_24' => 'All days of the week — 24 hrs a day',
    ],

    'daily_budget_bands' => [
        '100-500' => '$100 to $500',
        '500-1000' => '$500 to $1,000',
        '1000-1500' => '$1,000 to $1,500',
        '1500-2000' => '$1,500 to $2,000',
        '2000-2500' => '$2,000 to $2,500',
        '2500-3000' => '$2,500 to $3,000',
        '3000-3500' => '$3,000 to $3,500',
        '3500-4000' => '$3,500 to $4,000',
        '4000-4500' => '$4,000 to $4,500',
        '4500-5000' => '$4,500 to $5,000',
        '5000-6000' => '$5,000 to $6,000',
        '6000-7000' => '$6,000 to $7,000',
        '7000-8000' => '$7,000 to $8,000',
        '8000-9000' => '$8,000 to $9,000',
        '9000-10000' => '$9,000 to $10,000',
        'other' => 'Other amount',
    ],

    /*
    | Recommendation rules keyed by company size, per the spec. These
    | strings are surfaced to the advertiser after submission and saved
    | with the inquiry for admin review.
    */
    'recommendations_by_size' => [
        'micro' => [
            'Business listing page',
        ],
        'small' => [
            'Business listing page',
            'Ads on the business listing page',
            'Ads on the home page (except the slider ads)',
        ],
        'medium' => [
            'Home page slider ads',
            'Other ads on the home page',
        ],
        'large' => [
            'Home page slider ads',
            'Other ads on the home page',
            'Business listing page ad',
        ],
    ],

    // Extra recommendation when the lowest daily budget band is chosen.
    'recommendation_low_budget' => [
        'band' => '100-500',
        'options' => [
            'Side ads',
            'Deals of the day',
            'Placement next to the categories on the home page',
            'VOpen Market Lists top ten',
        ],
    ],
];
